### ISSUE TITLE
When the target table's primaryKey is not 'id' will error

### ISSUE THREAD

**Issue by ab0029** [overtrue/laravel-follow#100]
https://github.com/overtrue/laravel-follow/blob/3a5b50f919415972870b2d543840343e3f3a6ad3/src/Follow.php#L73-L81

If the target Model like this:
`<?php

namespace App
use Illuminate\Database\Eloquent\Model;
use Overtrue\LaravelFollow\Traits\CanBeFavorited;
class Goods extends Models {
    use CanBeFavorited;
    protected $primaryKey = 'goods_id';
}
`
// this will error : Unknown column 'id' in 'where clause'
$user->hasFavorited($goods);

The relationKey is The goods.goods_id  Or followable_id

**Comment by overtrue** [comment]
This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)
