### ISSUE TITLE
Trait 'Illuminate\Foundation\Events\Dispatchable' not found

### ISSUE THREAD

**Issue by t0x1c0d3r** [overtrue/laravel-follow#102]
hello guys...

i added this package to my laravel projects but after use follow() function return this error :

Trait 'Illuminate\Foundation\Events\Dispatchable' not found in ROOT/vendor/overtrue/laravel-follow/src/Events/Event.php on line 27

in User App Model i'm using : 
use CanFollow, CanBeFollowed;

please help me ;-(

**Comment by overtrue** [comment]
That the Laravel version？

**Comment by overtrue** [comment]
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Events/Dispatchable.php

**Comment by t0x1c0d3r** [comment]
hi dear.
/Illuminate/Foundation/Events/Dispatchable.php file is :

`<?php

/*
 * This file is part of the overtrue/laravel-follow
 *
 * (c) overtrue <i@overtrue.me>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Overtrue\LaravelFollow\Events;

use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use Overtrue\LaravelFollow\Follow;

/**
 * Class Event.
 *
 * @author overtrue <i@overtrue.me>
 */
class Event
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $causer;

    public $relation;

    public $targets;

    public $class;

    /**
     * Event constructor.
     *
     * @param \Illuminate\Database\Eloquent\Model   $causer
     * @param \Overtrue\LaravelFollow\Events\string $relation
     * @param int|array                             $targets
     * @param \Overtrue\LaravelFollow\Events\string $class
     */
    public function __construct(Model $causer, string $relation, $targets, string $class)
    {
        $this->causer = $causer;
        $this->relation = $relation;
        $this->targets = $targets;
        $this->class = $class;
    }

    public function getRelationType()
    {
        return Follow::RELATION_TYPES[$this->relation];
    }

    public function getTargetsCollection()
    {
        return \forward_static_call([$this->targets->classname, 'find'], (array) $this->targets);
    }
}
`

and my laravel version is : Laravel Framework version 5.2.45

wOw, i think should upgrade laravel framework , right :-?

**Comment by overtrue** [comment]
Yes.

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午3:43写道：

**Comment by t0x1c0d3r** [comment]
hello, i upgrade laravel framework to 5.8 and fixed this problem,
but now i when user followed another user record row inserted in database table followabes but $user->followers()->get() return nill :|

**Comment by overtrue** [comment]
$user->followings()->get();

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午5:11写道：

**Comment by t0x1c0d3r** [comment]
not working :((
please help me :(

$followers = $user->followers()->get();
$followings = $user->followings()->get();

return null.

**Comment by overtrue** [comment]
plz paste your context code.

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午5:15写道：

**Comment by t0x1c0d3r** [comment]
User Model : 

```
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Overtrue\LaravelFollow\Traits\CanBeFollowed;
use Overtrue\LaravelFollow\Traits\CanFollow;

class User extends Authenticatable
{
    use CanFollow, CanBeFollowed;

    ..........
}
```
UserController : 
 ```
$user = User::where('id', $user_id)->where('status', 1)->first();
 $count = count($user);

        if ($count) {

            $followers = $user->followers()->get();
            $followings = $user->followings()->get();
        }
```

return null,

in database row inserted and for secound request to follow row with target userId just updated created_at filed :(

**Comment by overtrue** [comment]
where is the follow code? you insert row manually?

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午5:21写道：

**Comment by t0x1c0d3r** [comment]
no, i use this code for follow user :

```
 if ($currentUser->follow($user)) {

                        \App\flash("followed Successfully !", "success");
                        return redirect()->route('User.Index',$user->id);
                    } else {

                        // error in follow
                    }
```

**Comment by overtrue** [comment]
dd($followers = $user->followers()->get();
$followings = $user->followings()->get(););

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午5:28写道：

**Comment by t0x1c0d3r** [comment]
Collection {#295 ▼
  #items: []
}

**Comment by overtrue** [comment]
it should be two collections.

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午5:33写道：

**Comment by t0x1c0d3r** [comment]
two collections return
#items: []

**Comment by overtrue** [comment]
and database table screenshots please.

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午5:35写道：

**Comment by t0x1c0d3r** [comment]
[http://oi67.tinypic.com/2crq8g5.jpg](url)

**Comment by t0x1c0d3r** [comment]
wOw, i delete followabe table and want to migrate again but return this error :

 `Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `followables` add index `followables_followable_type_index`(`followable_type`))
`

**Comment by t0x1c0d3r** [comment]
My Migration Up Function Content : 

```
public function up()
    {
        Schema::create(config('follow.followable_table', 'followables'), function (Blueprint $table) {
            $userForeignKey = config('follow.users_table_foreign_key', 'user_id');
            $table->unsignedBigInteger($userForeignKey);
            $table->unsignedBigInteger('followable_id');
            $table->string('followable_type')->index();
            $table->string('relation')->default('follow')->comment('follow/like/subscribe/favorite/upvote/downvote');
            $table->softDeletes();
            $table->timestamps();

            $table->foreign($userForeignKey)
                ->references(config('follow.users_table_primary_key', 'id'))
                ->on(config('follow.users_table_name', 'users'))
                ->onUpdate('cascade')
                ->onDelete('cascade');
        });
    }
```

**Comment by t0x1c0d3r** [comment]
i think migration error fixed by Schema::defaultStringLength(191);

**Comment by overtrue** [comment]
MySQL 5.7.7+ will support long index.

and the function `getCurrentUser()` will return `App\User`, the followable_type on your database is wrong, it should be `App\User`

**Comment by t0x1c0d3r** [comment]
function getCurrentUser()
{
    return User::where('id', getCurrentUserId())->first();
}

**Comment by overtrue** [comment]
OK, plz show me the context for `$user`.

> no, i use this code for follow user :
> 
> ```
>  if ($currentUser->follow($user)) {
> 
>                         \App\flash("followed Successfully !", "success");
>                         return redirect()->route('User.Index',$user->id);
>                     } else {
> 
>                         // error in follow
>                     }
> ```

**Comment by t0x1c0d3r** [comment]
$user = User::find($id);

                if (count($user) > 0) {

                    if ($currentUser->follow($user)) {

                        \App\flash("کاربر مورد نظر با موفقیت دنبال شد !", "success");
                        return redirect()->route('User.Index', $user->id);

                    } else {

                        // error in follow
                    }

**Comment by overtrue** [comment]
Sorry I cannot find the reason which caused the error, and the error is you
have wrong value of `followable_type` in database, the right value is
`App\User`. so please debug your code find the error logic. Thanks

t0x1c0d3r <notifications@github.com>于2019年5月8日 周三上午5:57写道：

**Comment by t0x1c0d3r** [comment]
Okay, thanks brO <3

**Comment by t0x1c0d3r** [comment]
i found solution.

change 

`$user = User::find($id);`

to

`$user = \App\User::find($id);`

first $user load from : Illuminate\Foundation\Auth\User
second $user load from : \App\User

thanks brO <3

**Comment by 01mrlast** [comment]
Hi sorry im install this package in laravel 7 give me this error , Can anyone help me?
![image](https://user-images.githubusercontent.com/51836304/86762903-3e615a80-c047-11ea-9b68-a52e18edb72c.png)

**Comment by overtrue** [comment]
@01mrlast plz note 2.0.0 has a breaking change, Your code is 1.x usage

https://github.com/overtrue/laravel-follow/releases/tag/2.0.0
