### ISSUE TITLE
Events getTargetsCollection should use ids

### ISSUE THREAD

**Issue by Frankisgek** [overtrue/laravel-follow#103]
```
public function getTargetsCollection()
{
        return \forward_static_call([$this->targets->classname, 'find'], (array) $this->targets);
}
```

should be

 ```
public function getTargetsCollection()
{
        return \forward_static_call([$this->targets->classname, 'find'], (array) $this->targets->ids);
}
```

The current function always returns an empty array.

**Comment by overtrue** [comment]
This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)
