### ISSUE TITLE
Don't you need fourth argument in `$this->morphedByMany` when use not default Eloquent named rules?

### ISSUE THREAD

**Issue by hokutoasari** [overtrue/laravel-follow#109]
It first, sorry my poor english. And Thank's great and useful package! I am honored to meet this package!

May be, I found some little bugs in follow features.

I used not default Eloquent named rules. `User` is default named rule, I used `UserEloquentEntity`.

And, I published config, not updated. (I used default published config file.)

Then called `followings()` method, I see following errors.

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'followables.user_eloquent_entity_id' in 'field list'

It seems like, does not use `config('follow.users_table_foreign_key')` value.

So, I read package's code and dived into laravel's `morphedByMany()` code.

Then I found following line in laravel's code.

`/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php`

```/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php
    public function morphedByMany($related, $name, $table = null, $foreignPivotKey = null,
                                  $relatedPivotKey = null, $parentKey = null, $relatedKey = null)
    {
        $foreignPivotKey = $foreignPivotKey ?: $this->getForeignKey();
```

This code are use `$this->setForeignKey()` when missing `$foreignPivotKey`.

But we have `$foreignKey` in following line.

https://github.com/overtrue/laravel-follow/blob/97b40d83478a4515f7cf40ce88ec5908cb0b1d69/src/Traits/CanFollow.php#L101

And, that value was not used in following line.

https://github.com/overtrue/laravel-follow/blob/97b40d83478a4515f7cf40ce88ec5908cb0b1d69/src/Traits/CanFollow.php#L106

So, laravel's code use default method `$this->getForeignKey()`.

And laravel's `$this->getForeignKey()` are this.

```php
    public function getForeignKey()
    {
        return Str::snake(class_basename($this)).'_'.$this->getKeyName();
    }
```

https://github.com/laravel/framework/blob/f0f1fb0778d829c688a69d6c09602bf7b430e6cc/src/Illuminate/Database/Eloquent/Model.php#L1487-L1490

It's works class name based.

But in this case, do not want to work class name based.

So, I think, need fourth arguments in

https://github.com/overtrue/laravel-follow/blob/97b40d83478a4515f7cf40ce88ec5908cb0b1d69/src/Traits/CanFollow.php#L106

this line.

like 

```php
        return $this->morphedByMany($class, config('follow.morph_prefix'), $table, $foreignKey)`
```

And, 

https://github.com/overtrue/laravel-follow/blob/97b40d83478a4515f7cf40ce88ec5908cb0b1d69/src/Traits/CanBeFollowed.php#L48

too like this.

```php
        return $this->morphToMany(config('follow.user_model'), config('follow.morph_prefix'), config('follow.followable_table'), null, $foreignKey)
```

How about this one?

**Comment by overtrue** [comment]
@hokutoasari This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)
