### ISSUE TITLE
FollowServiceProvider, boot method missing existing check

### ISSUE THREAD

**Issue by tnerbovik** [overtrue/laravel-follow#11]
To avoid recreating migrations. Nice library btw

if (!class_exists('CreateLaravelFollowTables')) {
}

**Comment by overtrue** [comment]
if the file exists, rerun the `vendor:publish` command will not copy the migration file. plz take a try.

**Comment by tnerbovik** [comment]
It will create a new migration file for every time I do vendor:publish

**Comment by overtrue** [comment]
@tnerbovik 

1. run `vendor:publish` 
2. modify the migration file: `/database/migrations/2017_06_08_190625_create_laravel_follow_tables.php`
3. rerun the command
4. check your modify. 

it will not override it. (5.4.23)

**Comment by overtrue** [comment]
Of course,  the result of `vendor:publish` always show `Copied File...`

**Comment by overtrue** [comment]
sorry, I found it 😆
