### ISSUE TITLE
Out-of-date package when installed with composer

### ISSUE THREAD

**Issue by Zontir** [overtrue/laravel-follow#113]
I have seen that when installing with composer the migrations still continue as before. The unsignedInteger field is still there. And who knows how many other things might be outdated.

How can I install with composer the latest version?

**Comment by overtrue** [comment]
Plz try again.

**Comment by Zontir** [comment]
> Plz try again.

The latest version is now correctly downloaded from composer without the need to place :dev-master param.

Thank you!
