### ISSUE TITLE
How to use isFollowing in vue.js?

### ISSUE THREAD

**Issue by jinxkitt108** [overtrue/laravel-follow#116]
If i load users on a Vue component, how will i use v-if condition statement?

**Comment by haleyngonadi** [comment]
You have to pass it as prop from blade or you have to get the value by running a method in vue!

**Comment by jinxkitt108** [comment]
this is what i did.
on my controller..i append isFollowing as a json attribute.

`public function findExpert()
    {
        $user = auth('api')->user();
        $experts = User::where('type', 'expert')->where('id', '!=', $user->id)->latest()->paginate(4);
        foreach($experts as $expert) {
            if(auth('api')->user()->isFollowing($expert)){
            $expert['isFollowing'] = true;
            }
            else{
                $expert['isFollowing'] = false;  
            }
            $followings = $expert->followings()->get()->count();
            $followers = $expert->followers()->get()->count();
            $expert['followings'] = $followings;
            $expert['followers'] = $followers;
        }
        return $experts;
    }`

and in my vue component, i use v-if directive, if isFollowing is true then show 'Unfollow' else 'Follow'.

**Comment by jinxkitt108** [comment]
how to display post of followed users only?

**Comment by overtrue** [comment]
This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)

**Comment by uyanik13** [comment]
```

  public function amIFollowing(Request $request)
  {
    if (!$this->user) {
      return $this->responseUnauthorized();
    }


    if ($this->user->isFollowing($request->following_id)) {
          
         return $this->responseResourceCreated('User is Following', true);

        }else{
            return $this->responseResourceCreated('User isnt Following', false);
        }   
  }
```
use this controller
