### ISSUE TITLE
Soft Deletes not being used

### ISSUE THREAD

**Issue by kfirba** [overtrue/laravel-follow#124]
Hey,

I've been looking for a simple "follow" package and ended up with your package.

I saw that in the migration file you add the `deleted_at` column to the table but there is nowhere where you actually soft-delete a record. every time I `unfollow` a user, the record is getting deleted (which is just fine). Is there really any reason to have this column?

Also, I played a bit with the package and there seem to be some indexes missing. I added the following indexes (works for Postgres):

```php
$table->unsignedBigInteger($userForeignKey)->index(); // Postgres does not automatically creates an index for a foreign key
// ...
$table->primary(['user_id', 'followable_type', 'followable_id', 'relation']);
$table->index(['followable_type', 'followable_id', 'relation']);
```
Thanks for the great package! :smile:

**Comment by overtrue** [comment]
@kfirba This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)
