### ISSUE TITLE
Can this be used with laravel-tagging?

### ISSUE THREAD

**Issue by milanchheda** [overtrue/laravel-follow#13]
Hi,

I am working on a project and wanted to check if this package can be used with [laravel-tagging](https://github.com/rtconner/laravel-tagging)? So every post has tags. 

**What I want?**
Users to like/follow tags and will see posts based on tags they liked, followed, etc. 

Just wanted to check if I can use the two packages together to achieve my requirement.

**Comment by overtrue** [comment]
I think it works, plz take a try.

**Comment by milanchheda** [comment]
Well, I tried and it works perfectly fine. Thanks!

**Comment by overtrue** [comment]
@milanchheda You are welcome.
