### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::whereNotNull does not exist.

### ISSUE THREAD

**Issue by krishna8723** [overtrue/laravel-follow#139]
![Screenshot from 2020-04-25 08-53-40](https://user-images.githubusercontent.com/19906424/80269777-6856e200-86d2-11ea-9571-e8ea340d9de9.png)

Hi, I am getting the above error while using: auth()->user()->followings. Please help.

**Comment by overtrue** [comment]
https://laravel.com/docs/7.x/collections#method-wherenotnull

**Comment by overtrue** [comment]
@krishna8723 where is version of your laravel framework ?

**Comment by overtrue** [comment]
https://github.com/laravel/framework/commit/dd4387b3c70dd0907af131ac9aaa627acbb30e8b
