### ISSUE TITLE
does this package allow to follow any model not just user?

### ISSUE THREAD

**Issue by jayenne** [overtrue/laravel-follow#140]
hi, 
Can I use this package to enable users to follow other users and to follow another model too? any number of models?

thanks.

**Comment by overtrue** [comment]
maybe you need this package: https://github.com/overtrue/laravel-subscribe

**Comment by jayenne** [comment]
Thank you for clearing that up.

So that I understand it correctly...
In my app I have 3 models... users, boards & posts. A user can "follow" another user and/or a board and/or a post to recieve notifictions/recommendations on any of the three.

Q1: should I be using follow for the user <-> user "follows"
and laravel-subscribe for the user <-> board & post "follows"

Q2: can a user be a subscriber and be subscribed to? Would this  make laravel-follow redunctant in my user-case?

Q3: is there a different approach you'd reccomend that I should be looking at my user-case?

**Comment by overtrue** [comment]
Users can follow each other and subscribe to other models to get changes notifications/recommendations.

Q1: Yes!
Q2: No, although the relationships between the models are very similar, they are indeed two relationships.

So, I think you can watch to events:  subscribed items changed and followed user has something created or updated, then send notifications or recommendations to subscriber and follower.

**Comment by jayenne** [comment]
Thank you

**Comment by overtrue** [comment]
@jayenne You're welcome.
