### ISSUE TITLE
Get all user you are not following

### ISSUE THREAD

**Issue by danialwafiy** [overtrue/laravel-follow#141]
Is there a way to get all users who I am not following?

**Comment by overtrue** [comment]
```php
User::whereDoesntHave('followers', function($q) {
  $q->where('users.id', auth()->id());
});
```

**Comment by danialwafiy** [comment]
@overtrue I'm getting all the users including myself. But when i follow the user, and refresh, they are still there.

**Comment by overtrue** [comment]
If you want to exclude your self: 

```php
User::whereDoesntHave('followers', function($q) {
  $q->where('users.id', auth()->id());
})
->where('users.id', '<>', auth()->id())
->get();
```

**Comment by danialwafiy** [comment]
Ok but I'm still getting the user i just followed. I'm login as user1 (id:1)
![Capture](https://user-images.githubusercontent.com/46147972/87930706-1e0bb400-cabb-11ea-9e79-194ce4ec855d.PNG)
![Capture](https://user-images.githubusercontent.com/46147972/87930747-311e8400-cabb-11ea-80d8-678b97dbe4c2.PNG)

**Comment by overtrue** [comment]
```php
$myUnfollowedUsers = User::whereNotIn(
            'id',
            function ($q) {
                $q->select('following_id')->from('user_follower')->where('follower_id', auth()->id());
            }
        )->where('id', '<>', auth()->id())->get()->toArray();
```

**Comment by danialwafiy** [comment]
works like a charm. thanks

**Comment by overtrue** [comment]
@danialwafiy 🤣
