### ISSUE TITLE
the toggleFollow() return null in respone 

### ISSUE THREAD

**Issue by asadullah097** [overtrue/laravel-follow#145]
I am using this package it is working fine but on the API it returns null how to fix?

**Comment by overtrue** [comment]
Indeed, because I'm not sure what is appropriate to return, because no exceptions thrown is considered successful, so you can actually ignore the return value, or if you have a better suggestion, very welcome to discuss!

**Comment by asadullah097** [comment]
thank you for the replay!
actually the toggleFollow() return null but the follow and unfollow are working once you refresh the page I used you in a real project but I want it will work on at the same time no refresh is needed for the following or unfollowing. and I am trying to fix it

**Comment by overtrue** [comment]
You can refer to a logical implementation I wrote about earlier: https://github.com/overtrue/yike.io/blob/master/src/components/buttons/relation-btn.vue#L53

**Comment by asadullah097** [comment]
Hello I solved with the simple  ajax method when the toggleFollow() executive I refresh the specific div  that is working perfectly

**Comment by overtrue** [comment]
@asadullah097 I'd love to know your solution.

**Comment by asadullah097** [comment]
will be waiting for the better solution

**Comment by overtrue** [comment]
toggle the local Vue data key maybe is a better solution:

```js
// 1. toggle local state first
this.followed = !this.followed;

// 2. the send the toggle request.
$axios.post(`/api/users/${targetUser.id}/toggle-follow`)
.catch(() => {
     // 3. toggle back when something went wrong.
     alert('failed to toggle follow.')
     this.followed = !this.followed;
})

```

**Comment by asadullah097** [comment]
I am using a blade template engine

**Comment by overtrue** [comment]
@asadullah097 Oh, I got it.
