### ISSUE TITLE
  Trait 'Overtrue\LaravelFollow\Traits\CanFavorite' not found

### ISSUE THREAD

**Issue by run100** [overtrue/laravel-follow#147]
PHP 7.3.24
Laravel Framework 5.8.38

composer.json
`
"require": {
    "php": "^7.1.3",
    "barryvdh/laravel-cors": "^1.0.4",
    "beyondcode/laravel-self-diagnosis": "^1.0",
    "erusev/parsedown-extra": "^0.7.1",
    "fideloper/proxy": "^4.0",
    "guzzlehttp/guzzle": "^6.3",
    "laravel/framework": "5.8.*",
    "laravel/passport": "^7.2",
    "laravel/tinker": "^1.0",
    "laravolt/avatar": "^2.0",
    "mews/purifier": "^2.1",
    "overtrue/easy-sms": "^1.0",
    "overtrue/laravel-emoji": "^1.0",
    "overtrue/laravel-filesystem-qiniu": "^1.0",
    "overtrue/laravel-follow": "dev-master",
    "overtrue/laravel-lang": "^3.0",
    "overtrue/laravel-socialite": "^2.0",
    "overtrue/laravel-uploader": "^1.0.0",
    "predis/predis": "^1.1",
    "sentry/sentry-laravel": "^1.0.1",
    "spatie/laravel-activitylog": "^3.2",
    "spatie/laravel-url-signer": "^2.2",
    "tamayo/laravel-scout-elastic": "^5.0",
    "tucker-eric/eloquentfilter": "^1.3",
    "vinkla/hashids": "^6.0"
  },
`
composer update 之后

`
  Trait 'Overtrue\LaravelFollow\Traits\CanBeVoted' not found
`

vendor / overtrue/ laravel-follow / src 也没有 Traits目录

**Comment by overtrue** [comment]
请不要在生产环境是用 `"overtrue/laravel-follow": "dev-master"` 这种写法，明确指定到哪个主版本， 你需要更新为 `"overtrue/laravel-follow": "^1.0"`
