### ISSUE TITLE
Trait "Overtrue\laravelFollow\Traits\CanFollow" not found

### ISSUE THREAD

**Issue by fastmarketo** [overtrue/laravel-follow#151]
![image](https://user-images.githubusercontent.com/6827222/112512862-c647ea00-8db9-11eb-8047-04bdeb6cd492.png)

```
Symfony\Component\ErrorHandler\Error\FatalError
Trait "Overtrue\LaravelFollow\Traits\CanFollow" not found
http://127.0.0.1:8000/
```
I have also done it:

![image](https://user-images.githubusercontent.com/6827222/112518150-1ffee300-8dbf-11eb-9ded-4e1c0efe42ef.png)

This is Laravel 7.

**Comment by overtrue** [comment]
It looks like your code is version 1.0, but you have installed version 2.0, so there are breaking changes. If you want to use the latest 2.0 version please change your code according to the version change log.

**Comment by fastmarketo** [comment]
Thank you so much for such a fast reply. I am following a course on udemy for Laravel but the author is unresponsive. If possible can you guide me or is there any such documentation that can help me so that I can make requisite changes. Thank you so much.

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-follow/blob/master/README.md

**Comment by dome272** [comment]
I have the same trouble using laravel 8.12 and using laravel-follow 2.2. I also tried reinstalling a bunch of times. Any ideas?
The error I get is: 
`PHP Fatal error:  Trait "Overtrue\LaravelFollow\Traits\CanBeFollowed" not found in C:\xampp\htdocs\lsapp\like\app\Models\Post.php on line 10

   Symfony\Component\ErrorHandler\Error\FatalError 

  Trait "Overtrue\LaravelFollow\Traits\CanBeFollowed" not found

  at C:\xampp\htdocs\lsapp\like\app\Models\Post.php:10
      6▕ use Overtrue\LaravelFollow\Traits\CanBeFollowed;
      7▕ use Illuminate\Database\Eloquent\Model;
      8▕
      9▕
  ➜  10▕ class Post extends Model
     11▕ {
     12▕        use CanBeFollowed;
     13▕
     14▕     protected $fillable = ['title'];


   Whoops\Exception\ErrorException 

  Trait "Overtrue\LaravelFollow\Traits\CanBeFollowed" not found

  at C:\xampp\htdocs\lsapp\like\app\Models\Post.php:10
      6▕ use Overtrue\LaravelFollow\Traits\CanBeFollowed;
      7▕ use Illuminate\Database\Eloquent\Model;
      8▕
      9▕
  ➜  10▕ class Post extends Model
     11▕ {
     12▕        use CanBeFollowed;
     13▕
     14▕     protected $fillable = ['title'];

  1   C:\xampp\htdocs\lsapp\like\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError("Trait "Overtrue\LaravelFollow\Traits\CanBeFollowed" not found", "C:\xampp\htdocs\lsapp\like\app\Models\Post.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()`

**Comment by JimChenWYU** [comment]
@dome272 looking at the package in your vendor directory to make sure you had install version 1.* .
