### ISSUE TITLE
这种情况下的 N+1 怎么解决

### ISSUE THREAD

**Issue by shijie1991** [overtrue/laravel-follow#157]
文章列表中

我是否关注了文章作者

**Comment by overtrue** [comment]
这个实际上可以通过加载关注关系后计算，不过我后面可以发布一个新版，自带这个方法，省去大家的烦恼，敬请期待。

**Comment by shijie1991** [comment]
期待 ing

**Comment by overtrue** [comment]
```php
$posts = Post::all();

$me->attachFollowStatus($posts, fn($post) => $post->author);

dd($posts->toArray());
```

**Comment by shijie1991** [comment]
Followable.php 195行

`$followables->map(function (Model $followable) use ($followed) {`

没有 use $resolver

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-follow/blob/master/src/Followable.php#L196

**Comment by shijie1991** [comment]
Followable.php 200行

`$followed->has($followable->getKey())`

改

`$followed->flip()->has($followable->getKey())`

**Comment by overtrue** [comment]
@shijie1991 哈哈，这 TM 巧合，测试用例的数量恰好小于索引长度。。。大意了大意了

**Comment by shijie1991** [comment]
嘻嘻 大佬牛逼
