### ISSUE TITLE
syntax error, unexpected '=>'

### ISSUE THREAD

**Issue by AlexKomMsk** [overtrue/laravel-follow#158]
Hello. After recent updates, I began to receive an error.
syntax error, unexpected '=>' (T_DOUBLE_ARROW)
/vendor/overtrue/laravel-follow/src/Followable.php:218

**Comment by overtrue** [comment]
From 2.x -> 3?

**Comment by AlexKomMsk** [comment]
I have updated all packages with "composer update". After that, an error appeared.
The error is here:
$resolver = $resolver ?? fn ($m) => $m;

**Comment by overtrue** [comment]
@AlexKomMsk Please upgrade to [2.4.3](https://github.com/overtrue/laravel-follow/releases/tag/2.4.3) to fix this.

**Comment by sdevore** [comment]
This has regressed in 2.4.5

**Comment by sdevore** [comment]
@overtrue this has regressed in the current release 2.4.5 see https://github.com/overtrue/laravel-follow/blob/2386dd55b94e57e4f4391b8fe5fc87890861e50c/src/Followable.php#L196

**Comment by overtrue** [comment]
@sdevore Sorry, I've released 2.4.6 to fix this. https://github.com/overtrue/laravel-follow/blob/2.4.6/src/Followable.php#L218
