### ISSUE TITLE
Feature request: Option to include pending requests in attachFollowStatus

### ISSUE THREAD

**Issue by bohemima** [overtrue/laravel-follow#161]
Would it make sense to add an option to include pending follow requests (or should they even be there by default?) The name of the method suggests that it should attach follow status, having a pending request is just that.

Naming is always hard, I'm not a fan of the `has` prefix (would is_following be a better name?) but since that would be a breaking change, let's not dive in to that :)

For a pending request, maybe another attribute called `has_following_request` and an option to the method, `$includePendingRequests`?

**Comment by overtrue** [comment]
what about `is_following` + `is_follow_accepted` ?

**Comment by bohemima** [comment]
> what about `is_following` + `is_follow_accepted` ?

I like that naming more but changing the already used convention will make a lot of people angry most likely :)

**Comment by bohemima** [comment]
Having the attribute configurable, with `has_following` as default maybe?

**Comment by overtrue** [comment]
@bohemima We can add them all, and then remove the old one after the next major version.

**Comment by overtrue** [comment]
```
is_following: true,
has_followed: true,
follow_accepted_at: '2021-07-08 00:00:00'
```

How about this?

**Comment by bohemima** [comment]
> ```
> is_following: true,
> has_followed: true,
> follow_accepted_at: '2021-07-08 00:00:00'
> ```
> 
> How about this?

I like the idea of the date!

**Comment by overtrue** [comment]
```
has_followed: true, // old
followed_at: true, // new
follow_accepted_at: '2021-07-08 00:00:00' // new
```

**Comment by overtrue** [comment]
@bohemima I have implement this feature like this: 

```
has_followed: true, // old
followed_at:  '2021-07-08 00:00:00' // new
follow_accepted_at: '2021-07-08 00:00:00' // new
```
