### ISSUE TITLE
Allow use of model with uuid

### ISSUE THREAD

**Issue by CodeGreedDevelopers** [overtrue/laravel-follow#162]
I published the migration and updated the following_id and follower_id to use uuid instead of id but when trying to follow a user i get the error "Typed property Overtrue\\LaravelFollow\\Events\\Event::$followerId must be int, string used"

**Comment by overtrue** [comment]
Please upgrade  to 2.4.4 to fix this.  #160

**Comment by CodeGreedDevelopers** [comment]
Okay thanks

**Comment by overtrue** [comment]
@CodeGreedDevelopers ❤️
