### ISSUE TITLE
Send follow request

### ISSUE THREAD

**Issue by Jacobtims** [overtrue/laravel-follow#166]
How can I make that a user actually can send a kind of follow request.
Now, when I user `toggleFollow()` or `follow()` it isn't sending a 'follow request', but the user is followed directly.

**Comment by jdesousa1** [comment]
Hi @Jacobtims

You need to put a method in the model that uses the Followable trait with your custom logic (or return true if always you need to send a request)

An example for the custom logic is if some users need to allow follow requests and others doesn't.

This overrides the default config.

```php
public function needsToApproveFollowRequests()
{
    // Your custom logic here
    return true;
}
```

**Comment by Jacobtims** [comment]
Thx for your fast reply!
I now gets a record with _accepted_at_ at NULL.
But it still counts the followers who sent a follow request.
How can I exclude the follow requests from the followers count?

**Comment by jdesousa1** [comment]
> Thx for your fast reply! I now gets a record with _accepted_at_ at NULL. But it still counts the followers who sent a follow request. How can I exclude the follow requests from the followers count?

Ok, you can add new basic where clause to the query.

I suppose you have the following code:
```php
$user->followers()->count();
```

So, if you need to get only accepted records:
```php
$user->followers()->whereNotNull('accepted_at')->count();
```

Also, you can get the 'follow requests' count:
```php
$user->followers()->whereNull('accepted_at')->count();
```

**Comment by vassilidev** [comment]
Hello,

I join the issue, i got the same problem but when i try to re send a follow request, i got many in the database, i can click 50 times on the button and the user got 50 followers, is it normal, i have to make my own verif ? I use ToggleFollow already

**Comment by overtrue** [comment]
@vassilidev It's a bug, I've fixed it., please upgrade to https://github.com/overtrue/laravel-follow/releases/tag/4.1.0
