### ISSUE TITLE
[PR] Add ApprovedFollowers Scope and NotApprovedFollowers Scope

### ISSUE THREAD

**Issue by vassilidev** [overtrue/laravel-follow#167]
Hello,

I ask you if you can add this scope by default to count ONLY approved Followers (Accepted_at !== null) or only where accepted_at is null, nothing hard.

Thank :D

**Comment by overtrue** [comment]
@vassilidev Hi, it's difficult to add scope to BelongsToMany, so I added 4 relations to support your request:

```php
$user->followings()->count();
$user->approvedFollowings()->count();
$user->notApprovedFollowings()->count();
```
> FYI: https://github.com/overtrue/laravel-follow/commit/1a539dfcc139b90f31e330b5ea037fc79c351408#diff-a4a2812dc47f1aa40ada614cf77c294f6098b18fdfba2534d0c6910deb2e5180R68-R91
