### ISSUE TITLE
Not able to use hasLiked

### ISSUE THREAD

**Issue by a-ssassi-n** [overtrue/laravel-follow#17]
`Auth::user() ` with `id:1` have liked a post with `id:119`

![capture](https://user-images.githubusercontent.com/7111734/28860924-3be87f0c-777c-11e7-9158-ea636913f309.PNG)

But when I try this:
`{{ dd (Auth::user()->hasLiked(119)) }}` **OR** `{{ dd (Auth::user()->hasLiked($post->id)) }}`
It return `false`

**Comment by overtrue** [comment]
`Auth::user()->hasLiked(119, 'App\Post')`

**Comment by a-ssassi-n** [comment]
I tried this, but still it's returning false.

**Comment by overtrue** [comment]
Looks like your database is a user liked another user, not liked a post.

**Comment by a-ssassi-n** [comment]
Please review this snapshot.

![capture](https://user-images.githubusercontent.com/7111734/28862498-e4c88f12-7782-11e7-9af7-4e28e55d466b.PNG)

The followable type is App\User in the database table. Where did I do wrong?

**Comment by overtrue** [comment]
yes, it means user:1 liked user:119

**Comment by overtrue** [comment]
$user = App\User::find(1);

dd($user->hasLiked(119)); // true

**Comment by a-ssassi-n** [comment]
But user:119 doesn't exists in the database. Also, when I do `(Auth::user()->hasLiked(119, 'App\User')` It also returns `false`.

**Comment by overtrue** [comment]
how does you inserted the data? can you show me the code?

**Comment by a-ssassi-n** [comment]
**User Model:**
```
use Overtrue\LaravelFollow\Traits\CanBeFollowed;
use Overtrue\LaravelFollow\Traits\CanFollow;
use Overtrue\LaravelFollow\Traits\CanLike;
class User extends Authenticatable
{
    use CanFollow, CanBeFollowed, CanLike;
```

**Post Model**
```
use Overtrue\LaravelFollow\Traits\CanBeLiked;
class Post extends Model
{
    use CanBeLiked;
```

**Controller**
```  
 public function likePost($postid)
    {
        $user = Auth::user();
        $user->toggleLike($postid);
        return Response::json(array(
                    'success' => true
                )); 
        //return redirect()->back()->with('message', 'Liked');
    }
```
And the route has a get method to call `likePost ` function

**Comment by overtrue** [comment]
if you are using id to created data, you must put the second argument like this:

```php
$post:  id: 119

// using id
$user->toggleLike(119, 'App\Post');

// using model
$user->toggleLike($post);
```

so, plz update the following line：

```php
$user->toggleLike($postid);
```

to 

```php
$user->toggleLike($postid, Post::class);
```

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-follow#parameters

**Comment by a-ssassi-n** [comment]
Thanks. It worked.

**Comment by overtrue** [comment]
😄
