### ISSUE TITLE
Making follows polymorphic

### ISSUE THREAD

**Issue by ams-ryanolson** [overtrue/laravel-follow#170]
I am not sure what your roadmap includes for this but I was wondering if there was any thoughts to making it polymorphic in the near future. Follow is one of those things that can be related to multiple models not just users. I would be interested in helping you accomplish this sooner than later with a donation if that would help

**Comment by overtrue** [comment]
@ams-ryanolson Hi, maybe you need https://github.com/overtrue/laravel-subscribe ?

**Comment by ams-ryanolson** [comment]
@overtrue in someways, yes, that is correct it would work, however, when it comes to naming conventions, subscribe is also a term used for purchase of a membership, so there becomes a conflict in naming conventions. 

Edit: You also have some features in follow such as approval that do not exist in subscribe.

**Comment by overtrue** [comment]
@ams-ryanolson OK, I will add this feature is a few days.

**Comment by ams-ryanolson** [comment]
@overtrue I was wondering how this was coming along?

**Comment by overtrue** [comment]
> @overtrue I was wondering how this was coming along?

Hi, I'm already working on it, but it's a Chinese holiday and I'm traveling with my family, so progress may not be as fast, I'll open a new branch to share the progress, you can see my work and try the new version in the 5.x branch then. And this will be a breaking change, both in the names of the database tables and in some of the APIs. So, it may take some time for testing, so please be patient. Thanks.

**Comment by ams-ryanolson** [comment]
@overtrue Thanks - ill gladly take a look at your progress and offer any suggestions or breaking issues I find within that branch!

**Comment by overtrue** [comment]
@ams-ryanolson 

### What’s Changed
- Default table name `user_followers` changed to `followables`.
- Renamed `followers.follower_id` to `user_id`(you can change it in the config file `app/follow.php`).
- `follow()`, `unfollow()` and `toggleFollow()` only accept model used `Overtrue\LaravelFollow\Traits\Followable`  trait now.
- Removed `Followable::areFollowingEachOther` method.
- `rejectFollowRequestFrom()`, `acceptFollowRequestFrow()`, `hasRequestedToFollow()` and `isFollowedBy` only accept model used `Overtrue\LaravelFollow\Traits\Follower` triat now.
- Rename event property `followingId`  to `followable_id`.
- Added event property  `followable_type`.
- Added event property  `user_id`.

You can try this version with the following command:

```bash
$ composer require overtrue/laravel-follow:5.x-dev
```

Looking forward to your feedback!

**Comment by ams-ryanolson** [comment]
Sorry for the delay. I have done SOME testing and so far it seems to be working well. 

I do not have the time but the readme for the 5.x branch is inaccurate in a few places. It looks like you copied some of it from another project of yours. 

Otherwise I have NOT found any issues. If anything comes up ill let you know!

**Comment by ams-ryanolson** [comment]
Bug found: a user should not be able to follow themself. Not sure if this is something you would want me to write a rule around or if this is something you feel you should add to it.

**Comment by overtrue** [comment]
> Bug found: a user should not be able to follow themself. Not sure if this is something you would want me to write a rule around or if this is something you feel you should add to it. 

Thanks, I will fix that.

**Comment by overtrue** [comment]
@ams-ryanolson I've released [5.0.0](https://github.com/overtrue/laravel-follow/releases/tag/5.0.0).
