### ISSUE TITLE
Getting same error in Model all the time

### ISSUE THREAD

**Issue by Shubhamlmp** [overtrue/laravel-follow#171]
Undefined type 'Overtrue\LaravelFollow\Traits\CanBeLiked'.

**Comment by overtrue** [comment]
#151

**Comment by Shubhamlmp** [comment]
It gives the same error for all other packages.
Undefined type 'Overtrue\LaravelVote\Traits\Voter'.

**Comment by Shubhamlmp** [comment]
Can you please give me an exact tutorial where I have to use which files?
and the other thing is you have a lot of packages like CanBeLiked and Liker I am confused about which package I have to use.
and my project deadline is very near.

**Comment by overtrue** [comment]
If you are really anxious to solve the problem, you should provide more context, installation steps, business code, etc., otherwise it is hard to help you.

**Comment by Shubhamlmp** [comment]
Okay, Currently I am wokring on Online discussion forum and for that I want to add vote section for questions and like dislike section for answers and all these functionalities using ajax so page not reload.

I am using Laravel v9 and php v8

**Comment by overtrue** [comment]
@Shubhamlmp please follow this document：https://github.com/overtrue/laravel-vote#installing

**Comment by overtrue** [comment]
like and dislike: https://github.com/overtrue/laravel-like
