### ISSUE TITLE
Error Traits

### ISSUE THREAD

**Issue by Bolibick** [overtrue/laravel-follow#172]
Symfony \ Component \ ErrorHandler \ Error \ FatalError

App\Models\User cannot use Overtrue\LaravelFollow\Followable - it is not a trait

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Notifications\Notifiable;

use Laravel\Fortify\TwoFactorAuthenticatable;

use Laravel\Jetstream\HasProfilePhoto;

use Laravel\Jetstream\HasTeams;

use Laravel\Sanctum\HasApiTokens;

use Overtrue\LaravelFollow\Followable;

class User extends Authenticatable

{

    use HasApiTokens;

    use HasFactory;

    use HasProfilePhoto;

    use HasTeams;

    use Notifiable;

    use TwoFactorAuthenticatable;

    use Followable;

**Comment by Bolibick** [comment]
I follow this : https://github.com/overtrue/laravel-follow/blob/master/README.md#laravel-follow

But i have the same error... Im in laravel 9 

Installing
composer require overtrue/laravel-follow -vvv
Configuration and Migrations
php artisan vendor:publish
Usage
Traits
Overtrue\LaravelFollow\Followable
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Overtrue\LaravelFollow\Followable;

class User extends Authenticatable
{
    <...>
    use Followable;
    <...>
}

**Comment by overtrue** [comment]
sorry, the newest version is 5.x, I forgot set the default branch to 5.x,  please follow the new README.md docs, thanks.

**Comment by Bolibick** [comment]
> sorry, the newest version is 5.x, I forgot set the default branch to 5.x, please follow the new README.md docs, thanks.

Thanks bro but i the same error traits Follower... I removed and reinstalled. I do this steps:

1) composer require overtrue/laravel-follow -vvv

2) php artisan vendor:publish         (I select yhe option 11 that is "Overtrue\LaravelFollow\FollowServiceProvider"

3) I add the two traits Followable and Follower in App/Models/User.php
This is the code that i have:

<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;
use Overtrue\LaravelFollow\Followable;
use Overtrue\LaravelFollow\Traits\Follower;




class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use Followable;
    use Follower;
    



And the error is:
App\Models\User cannot use Overtrue\LaravelFollow\Followable - it is not a trait

**Comment by Bolibick** [comment]
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;
use Overtrue\LaravelFollow\Followable;
use Overtrue\LaravelFollow\Traits\Follower;




class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use Followable;
    use Follower;

**Comment by Bolibick** [comment]
`<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;
use Overtrue\LaravelFollow\Followable;
use Overtrue\LaravelFollow\Traits\Follower;




class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use Followable;
    use Follower;
    `

**Comment by Bolibick** [comment]
This is the same error:

Symfony \ Component \ ErrorHandler \ Error \ FatalError

App\Models\User cannot use Overtrue\LaravelFollow\Followable - it is not a trait

**Comment by Bolibick** [comment]
here is missing Traits? in use Overtrue\LaravelFollow\Followable;
https://github.com/overtrue/laravel-follow/blob/5.x/README.md#overtruelaravelfollowfollowable

**Comment by overtrue** [comment]
@Bolibick sorry, I've fixed the typo.

**Comment by Bolibick** [comment]
Now it works bro ;)
Thanks for your help and support.

**Comment by overtrue** [comment]
@Bolibick ❤️
