### ISSUE TITLE
config key typo

### ISSUE THREAD

**Issue by ahmedesa** [overtrue/laravel-follow#174]
https://github.com/overtrue/laravel-follow/blob/ce6cf9e4a11af82079f20e87fb246da48f21962c/src/Traits/Follower.php#L107

key has to be
 config('follow.followables_model', \Overtrue\LaravelFollow\Followable::class)

**Comment by ahmedesa** [comment]
fix https://github.com/overtrue/laravel-follow/pull/175

**Comment by overtrue** [comment]
Thank you.
