### ISSUE TITLE
Question: How to send notification/email to user when they have a new follower?

### ISSUE THREAD

**Issue by samialtaher** [overtrue/laravel-follow#176]
Hello, 
Thanks for the great package. I just started using it on Laravel 8. I know there is an even triggered when a follow happens, but can someone please point me how to use this to send a notification or email to the user telling them "you have a new follower: <name_of_follower>" kind of message.

Thanks again for any help.
PS: I am just an 57 yr old guy just starting with Laravel (not even a developer, but an enthusiast. Help is highly appreciated)

**Comment by overtrue** [comment]
Hi @samialtaher 

Before you start the following steps, please read the official documentation first:
> https://laravel.com/docs/9.x/mail

1. First, you need to create a mail object:

```bash
php artisan make:mail NewFollower --markdown=emails.new-follower
```

Then update its code as follows:

*app/Mail/NewFollower*

```php
class NewFollower extends Mailable
{
    use Queueable, SerializesModels;
 
    public $follower;
 
    public function __construct(User $follower)
    {
        $this->follower = $follower;
    }
 
    public function build()
    {
        return $this->markdown('emails.new-follower');
    }
}
```

2. Edit the mail template `resources/views/emails/new-follower.blade.php`:

```blade
@component('mail::message')

  Your have a new follower {{ $follower->nickname }}!

Thanks,<br>
{{ config('app.name') }}
@endcomponent
```

3. Create the followed event listener:

```bash
php artisan make:listener NewFollowerListener --event=\\Overtrue\\LaravelFollow\\Events\\Followed
```

then update it's code as follows: 

*app/Listeners/NewFollowerListener.php*
```php
<?php

namespace App\Listeners;

use App\Mail\NewFollower;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Mail;
use Overtrue\LaravelFollow\Events\Followed;

class NewFollowerListener
{
    public function handle(Followed $event): void
    {
        $user = User::find($event->followable_id);
        $follower = User::find($event->follower_id);

        Mail::to($user)->send(new NewFollower($follower));
    }
}
```

4. Register the listener:

*app/Providers/EventServiceProvider.php*
```php
protected $listen = [
    //<...>
    \Overtrue\LaravelFollow\Events\Followed::class => [\App\Listeners\NewFollowerListener::class],
];
```

5. Done.

**Comment by samialtaher** [comment]
Hello,
Thanks for your help. I tried to implement this, but i get the following error:

[2022-06-30 07:50:32] production.ERROR: Undefined property: Overtrue\LaravelFollow\Events\Followed::$followable_id {"userId":44,"exception":"[object] (ErrorException(code: 0): Undefined property: Overtrue\\LaravelFollow\\Events\\Followed::$followable_id at /usr/home/mysite.net/htdocs/app/Listeners/NewFollowerListener.php:16)

The listener have the exact code you provided (also added use App\Models\User because it complained about it also)

`<?php

namespace App\Listeners;

use App\Models\User;
use App\Mail\NewFollower;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Mail;
use Overtrue\LaravelFollow\Events\Followed;

class NewFollowerListener
{
    public function handle(Followed $event): void
    {
        $user = User::find($event->followable_id);
        $follower = User::find($event->follower_id);

        Mail::to($user)->send(new NewFollower($follower));
    }
}
`

Can you tell me why it is not working? Thanks

Please note i am on Laravel 8 for this project. But when i checked the event these variables are there despite being on an earlier version of the package, so i am confused. Your help please. Thanks

**Comment by overtrue** [comment]
Please confirm the version of the package:

```bash
composer info overtrue/laravel-follow
```

**Comment by samialtaher** [comment]
Here is the output of the command:

name     : overtrue/laravel-follow
descrip. : User follow unfollow system for Laravel.
keywords :
versions : * 3.1.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage :
source   : [git] https://github.com/overtrue/laravel-follow.git f8eeb0823a3999d3ebecd7ba9f8c8ab41a4d64ce
dist     : [zip] https://api.github.com/repos/overtrue/laravel-follow/zipball/f8eeb0823a3999d3ebecd7ba9f8c8ab41a4d64ce f8eeb0823a3999d3ebecd7ba9f8c8ab41a4d64ce
path     : /usr/home/mysite.net/htdocs/vendor/overtrue/laravel-follow
names    : overtrue/laravel-follow

support
issues : https://github.com/overtrue/laravel-follow/issues
source : https://github.com/overtrue/laravel-follow/tree/3.1.1

autoload
psr-4
Overtrue\LaravelFollow\ => src

requires
laravel/framework ^8.0

requires (dev)
brainmaestro/composer-git-hooks ^2.7
friendsofphp/php-cs-fixer ^3.0
mockery/mockery ^1.2
orchestra/testbench ^6.0
phpunit/phpunit ^9.0

**Comment by overtrue** [comment]
OK, it's 3.x, so you need update the code of listener:

*app/Listeners/NewFollowerListener.php*

```
<?php

namespace App\Listeners;

use App\Mail\NewFollower;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Mail;
use Overtrue\LaravelFollow\Events\Followed;

class NewFollowerListener
{
    public function handle(Followed $event): void
    {
        $user = User::find($event->followingId);
        $follower = User::find($event->followerId);

        Mail::to($user)->send(new NewFollower($follower));
    }
}
```

**Comment by samialtaher** [comment]
Thank you very much. I really appreciate your help and time. 

Just to point out that I had to also include

use App\Models\User 

in both listener and Mail object.

One last question:
How can i include/pass the name of the user to the email markdown blade so the message is lie:

Hello (user name)  **<-- how can i get this variable to the blade?**

You have a new follower ( follower name )  <--- This is OK and passed

I tried to use Hello {{ $user->first_name }}, But this is passing the follower first name NOT the person being followed!

and again, very much appreciate your help.

**Comment by overtrue** [comment]
1. Added current user to Mail object:

```php
//app/Mail/NewFollower.php

class NewFollower extends Mailable
{
    use Queueable, SerializesModels;
 
    public $follower;
    public $user;
 
    public function __construct(User $user, User $follower)
    {
        $this->user = $user;
        $this->follower = $follower;
    }
 
    public function build()
    {
        return $this->markdown('emails.new-follower');
    }
}
```

2. Update template

```blade
@component('mail::message')

  Hello, {{ $user->first_name }},  Your have a new follower {{ $follower->first_name }}!

Thanks,<br>
{{ config('app.name') }}
@endcomponent
```

3. Update listener 

```php
class NewFollowerListener
{
    public function handle(Followed $event): void
    {
        $user = User::find($event->followingId);
        $follower = User::find($event->followerId);

        Mail::to($user)->send(new NewFollower($user, $follower));
    }
}
```

**Comment by samialtaher** [comment]
Hello again, thanks very much. All working great. Appreciated. Not only you helped get this working but also, helped me learn a lot of new stuff especially on Listeners and Mail / Notifications. Thanks!

This has become like a full tutorial on sending an email notification for follow events - Great!

Just a thought, what additional is needed if i want to use laravel notifications as well (database) ?

I already have the notifications table setup, and i am using it to show admin notifications for new user registrations.

So I guess, we would need to add a notification: php artisan make: notification NewFollowNotification

Inside the new file App\Notifications\NewFollwNotification.php - added the following code:

```

<?php

namespace App\Notifications;

use App\Models\User;
use App\Listeners\NewFollowerListener;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Overtrue\LaravelFollow\Events\Followed;

class NewUserFollowNotification extends Notification
{
    use Queueable;

   public $follower;
   public $user;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct(User $user, User $follower)
    {
        $this->user = $user;
        $this->follower = $follower;
        
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['database'];
    }

    
    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        

        return [
            'message' => 'You have a new follower',
            'Followerfirst' => $this->follower->first_name,
            'Followerlast' => $this->follower->last_name,
        ];
    }
}

```

and edited the Listener to call the notification: Notification::send($user, new NewUserFollowNotification($user, $follower));

```
<?php

namespace App\Listeners;

use App\Notifications\NewFollowNotification;
use App\Models\User;
use App\Mail\NewFollower;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;
use Overtrue\LaravelFollow\Events\Followed;

class NewFollowerListener
{
    public function handle(Followed $event): void
    {
        $user = User::find($event->followingId);
        $follower = User::find($event->followerId);

        Mail::to($user)->send(new NewFollower($user, $follower));
        Notification::send($user, new NewFollowNotification($user, $follower));
    }
}

```
Now i also get the data in the notification added to the database, and able to show it to the logged in user in their dashboard:
```
<div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                   <h6 class="mb-0"> Notifications </h6>
                </div>

                <div class="card-body">
                    @if(session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if(auth()->user())
                        @forelse($notifications as $notification)
                            <div class="alert alert-success" role="alert">
                                [{{ $notification->created_at }}] User {{ $notification->data['first_name'] }} {{ $notification->data['last_name'] }} ({{ $notification->data['email'] }}) has just registered.
                                <div class="text-end">
                                <a href="/markoneAsRead/{{ $notification->id }}" class=" mark-as-read"   data-id="{{ $notification->id }}">
                                    Mark as read
                                </a>
                                </div>
                            </div>

                            @if($loop->last)
                                <a href="{{ route('mark') }}" id="mark-all">
                                    Mark all as read
                                </a>
                            @endif
                        @empty
                            There are no new notifications
                        @endforelse
                    @else
                        No new Notifications!
                    @endif
                </div>
            </div>
        </div>
    </div>
```
Of course I already have the routes and methods for marking notifications as read:
```
Route::get('/markAsRead', function(){

	auth()->user()->unreadNotifications->markAsRead();

	return redirect()->back();

})->name('mark');

Route::get('/markoneAsRead/{id}', function(Request $request){

	auth()->user()
            ->unreadNotifications
            ->where('id', $request->id)
            ->markAsRead();

	return redirect()->back();

})->name('markone');

```
===

I added this for the benefits of other people who may want to do something similar.

Thanks again for all your help.

**Comment by overtrue** [comment]
Hi, @samialtaher Using Laravel notification is indeed a more recommended way. 

1. Just like [the documentation says](https://laravel.com/docs/9.x/notifications#using-the-notifiable-trait), let's add the `Notifiable` trait to the User model:

```php
<?php
 
namespace App\Models;
 
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
 
class User extends Authenticatable
{
    use Notifiable;
}
``` 

2. A notification that is distributable through multiple **channels**, so in addition to the `database`, you can also distribute your notification objects through `mail` and [any other possible channel](https://laravel.com/docs/9.x/notifications#specifying-delivery-channels):

*App\Notifications\NewUserFollowNotification.php*

```php
    //<...>
    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail', 'database'];
    }
```

So you also need to add its exclusive message [to the mail channel](https://laravel.com/docs/9.x/notifications#mail-notifications) by `toMail` method:

*App\Notifications\NewUserFollowNotification.php*
```php
public function toMail($notifiable)
{
    return new NewFollower($notifiable, $this->follower);
}
```

PS: There is no need to store the current user in the notification class, because the recipient of the notification `$notifiable` is the current user, so the complete code of your notification class could look like this:

```php

<?php

namespace App\Notifications;

use App\Models\User;
use App\Mails\NewFollower;
use App\Listeners\NewFollowerListener;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Overtrue\LaravelFollow\Events\Followed;

class NewUserFollowNotification extends Notification
{
    use Queueable;

   public $follower;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct(User $follower)
    {
        $this->follower = $follower;
        
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail', 'database'];
    }

    public function toMail($notifiable)
    {
        // $notifiable is current user (App\Models\User)
        return new NewFollower($notifiable, $this->follower);
    }

    
    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            'message' => 'You have a new follower',
            'Followerfirst' => $this->follower->first_name,
            'Followerlast' => $this->follower->last_name,
        ];
    }
}
```

3. Then update your listener as follows:

*App\Notifications\NewFollowerListener.php*

```diff
 public function handle(Followed $event): void
    {
        $user = User::find($event->followingId);
        $follower = User::find($event->followerId);

-       Mail::to($user)->send(new NewFollower($user, $follower));
-       Notification::send($user, new NewFollowNotification($user, $follower));
+      $user->notify(new NewUserFollowNotification($follower));
    }
```

All done.

**Comment by overtrue** [comment]
@samialtaher Hi, there is a typo: 

```diff
- App\Notifications\NewFollwNotification.php
+ App\Notifications\NewUserFollowNotification.php
```

**Comment by samialtaher** [comment]
Thanks very much for all your help. Really appreciated. 

This has become a great tutorial now. 

I will close this now.
