### ISSUE TITLE
get General error: 1 no such table: followables error

### ISSUE THREAD

**Issue by 0xezady** [overtrue/laravel-follow#177]
i want use this package
but when i run 
$user1->follow($user2); 
i get 
Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: 1 no such table: followables (SQL: select * from "followables" where "followables"."user_id" = 1 and "followables"."user_id" is not null and ("followable_id" = 2 and "followable_type" = App\Models\User) limit 1)'

error

**Comment by overtrue** [comment]
1. You need to add migration files:

```bash
php artisan vendor:publish
```

Select `Overtrue\\LaravelFollow\\FollowServiceProvider` and input the number.

2. Run migrate:

```bash
php artisan migrate
```

**Comment by 0xezady** [comment]
i do this but did not answer

**Comment by overtrue** [comment]
please the result of every command.

**Comment by 0xezady** [comment]
php artisan vendor:publish:
Which provider or tag's files would you like to publish?
  Publish files from all providers and tags listed below ................................................ 0
  Provider: Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider .......................................... 1
  Provider: Illuminate\Foundation\Providers\FoundationServiceProvider ................................... 2
  Provider: Illuminate\Mail\MailServiceProvider ......................................................... 3
  Provider: Illuminate\Notifications\NotificationServiceProvider ........................................ 4
  Provider: Illuminate\Pagination\PaginationServiceProvider ............................................. 5
  Provider: Laravel\Sail\SailServiceProvider ............................................................ 6
  Provider: Laravel\Sanctum\SanctumServiceProvider ...................................................... 7
  Provider: Laravel\Tinker\TinkerServiceProvider ........................................................ 8
  Provider: Livewire\LivewireServiceProvider ............................................................ 9
  Provider: Overtrue\LaravelFollow\FollowServiceProvider ............................................... 10
  Provider: Spatie\LaravelIgnition\IgnitionServiceProvider ............................................. 11
  Tag: config .......................................................................................... 12
  Tag: flare-config .................................................................................... 13
  Tag: ignition-config ................................................................................. 14
  Tag: laravel-errors .................................................................................. 15
  Tag: laravel-mail .................................................................................... 16
  Tag: laravel-notifications ........................................................................... 17
  Tag: laravel-pagination .............................................................................. 18
  Tag: livewire ........................................................................................ 19
  Tag: livewire:assets ................................................................................. 20
  Tag: livewire:config ................................................................................. 21
  Tag: livewire:pagination ............................................................................. 22
  Tag: migrations ...................................................................................... 23
  Tag: sail ............................................................................................ 24
  Tag: sail-bin ........................................................................................ 25
  Tag: sail-docker ..................................................................................... 26
  Tag: sanctum-config .................................................................................. 27
  Tag: sanctum-migrations .............................................................................. 28

php artisan migrate:
INFO  Nothing to migrate.

**Comment by overtrue** [comment]
```bash
ls -al ./app/database/migrations | grep follow
```

**Comment by 0xezady** [comment]
ls: ./app/database/migrations: No such file or directory

**Comment by overtrue** [comment]
```bash
ls -al ./app/databases/migrations | grep follow
```

**Comment by 0xezady** [comment]
result of this command:
ls: ./app/databases/migrations: No such file or directory

**Comment by overtrue** [comment]
ls -al .database/migrations | grep follow

**Comment by 0xezady** [comment]
it is return no result

**Comment by 0xezady** [comment]
i manually make followables table and it is work now

**Comment by overtrue** [comment]
OK.
