### ISSUE TITLE
$user->followings not working properly 

### ISSUE THREAD

**Issue by IslamHeza** [overtrue/laravel-follow#178]
$user->followings    
give me this :
{
                "id": 4,
                "user_id": 4,
                "followable_type": "App\\Models\\User",
                "followable_id": 3,
                "accepted_at": "2022-12-15T00:40:51.000000Z",
                "created_at": "2022-12-15T00:40:51.000000Z",
                "updated_at": "2022-12-15T00:40:51.000000Z"
 } 

not user object like the followers ... any help ?!

thanks

**Comment by overtrue** [comment]
```php
$followings = $user->followings()->with('followable')->get();

foreach($followings as $following)
{
    $following->followable; // this is the object which $user followed
}
```

**Comment by IslamHeza** [comment]
Thanks

**Comment by Yum1962** [comment]
@overtrue 
Hi hope you are having a great day.

I tried to apply the solution informed by you in the comment above, but it does not return an object. How can I get "followings" that return an object, as with "followers"?

Thanks in advance follow my code below, any help is welcome.

returns  this -->
`[{"id":60,"user_id":5,"followable_type":"App\\Models\\User","followable_id":9,"accepted_at":"2022-12-20T20:36:49.000000Z","created_at":"2022-12-20T20:36:49.000000Z","updated_at":"2022-12-20T20:36:49.000000Z"}]`

code -->

`<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="followers" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="row pl-5">
            @include('userList', ['users'=>$user->followers()->paginate(1)])
        </div>
    </div>

</div>

<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="followers" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="row pl-5">
            @include('userList', ['users'=>$user->followings()->paginate(1)])
        </div>
    </div>

</div>

@foreach($user as $following)

 {{$user->followings}}

@endforeach`

**Comment by Yum1962** [comment]
@overtrue if possible visit my repository created specifically for this issue there I uploaded all files related to this issue. Thank you very much in advance. sorry to bother https://github.com/applive3/laravelfollowingproblem

**Comment by overtrue** [comment]
@applive3 because your code is wrong, please see this example and try: https://github.com/overtrue/laravel-follow/issues/178#issuecomment-1352490749

**Comment by Ohislawrence** [comment]
> ```
> $following->followable;
> ```

Nice... will the documentation change soon?
