### ISSUE TITLE
how to recover data from the "following" user?

### ISSUE THREAD

**Issue by Yum1962** [overtrue/laravel-follow#179]
how to recover data from the "following" user?

I'm trying to retrieve the "following" date but I can't, how can I retrieve, for example, the name of the "followings"?
Thanks in advance.
My HomeController -->

`   public function userFollow($username)
    {
        $user = User::where('username', $username)->firstOrFail();

        $posts = Post::where('user_id', $user->id)->simplePaginate(3);
        $user = User::find($user->id);
        $followings = User::with('followings')->get();

        return view('/@')->with(['user' => $user, 'posts' => $posts, 'followings' => $followings]);

    }`

@foreach($followings as $following)

 {{$following->username}} --> problem returns all users in system :(

@endforeach

**Comment by overtrue** [comment]
Hi, @applive3  `User::with('followings')->get();` This is written to query the entire user table, of course.
if you want to get `$user`‘s followings, you can write as following:

```php
public function userFollow($username)
{
    $user = User::where('username', $username)->firstOrFail();
    $posts = Post::where('user_id', $user->id)->simplePaginate(3);
    $followings = $user->followings;

    return view('/@')->with(['user' => $user, 'posts' => $posts, 'followings' => $followings]);

}
```
and view:

```
@foreach($followings as $following)

username: {{ $following->followable->username }} 
followed_at: {{ $following->created_at }}

@endforeach
```

**Comment by Yum1962** [comment]
@overtrue  thanks :)
