### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by exzib** [overtrue/laravel-follow#18]
This is a wonderful addon that I have been using for my social portfolio website, it works wonders.

However, right now I am using Debugbar to see what queries takes long time, and it seems like laravel-follow is using a lot on our dashboard where we have a social feed like facebook.

Is there any simple way to cache laravel followable?

**Comment by overtrue** [comment]
Thank you, can you provide some screenshots?

**Comment by exzib** [comment]
Basicially laravel has caching that works like this:
(This is example from my project)

```
          $m_investments = Cache::remember('m_investments'.$user->id, 60, function()
          {
            return ManualInvestment::where([['userid', '=', $user->id]])->get();
          });
```

Basicially what laravel follow could do is cache stuff and reset the cache when something has updated, this increases loadtime overall and when something changes it just increases loadtime for 1 user.

**Comment by overtrue** [comment]
@exzib Thanks, You can add caching support in your own business logic.
