### ISSUE TITLE
Feature Request: Followers you know

### ISSUE THREAD

**Issue by ArtMin96** [overtrue/laravel-follow#180]
It would be great if this package support followers you know thing!

**Comment by overtrue** [comment]
Hello, can you give an example to elaborate on this?

**Comment by ArtMin96** [comment]
Something like this. Thanks.

![122854587-8f8a5d00-d331-11eb-9b9e-50a5851cd665](https://user-images.githubusercontent.com/29732308/209787270-29a4acea-1766-4133-815b-393494ca21d5.png)

Or users who are followed by your follower.

**Comment by ams-ryanolson** [comment]
@ArtMin96 You can actually build this yourself due to the complexity of what would need to be done. 

So create something like this. 
```
public function getMutualFollowers()
{
    // Get the list of all users that you are following
    $followings = Follow::followings();

    // Get the list of all users that are following you
    $followers = Follow::followers();

    // Find the intersection between the two collections to get the mutual followers
    $mutualFollowers = $followings->intersect($followers);

    return $mutualFollowers;
}
```

This is just one way to do it. Depending on your need, there are other ways, but this will return what you want in the end. You can also return something like this which would give you what you showed above. 

```
public function getMutualFollowers()
{
    // Get the list of all users that you are following
    $followings = Follow::followings();

    // Get the list of all users that are following you
    $followers = Follow::followers();

    // Find the intersection between the two collections to get the mutual followers
    $mutualFollowers = $followings->intersect($followers);

    // Get the count of the mutual followers
    $count = $mutualFollowers->count();

    // Get 3 random names from the mutual followers collection
    $names = $mutualFollowers->random(3)->pluck('name')->all();

    return [
        'count' => $count,
        'names' => $names,
    ];
}
```
I broke this down and such but this is the idea of the logic behind it.

**Comment by ArtMin96** [comment]
@ams-ryanolson Thank you very much for your help and time. I will use this option temporarily until I find a more optimal version because, for example, if the user has thousands of followers or followings, a performance problem may arise. If I have time, I'll try to get it through a query. If I get something, I'll post it here, maybe others will find it useful.

**Comment by ams-ryanolson** [comment]
@ArtMin96 I was just working on that for you. Again, I am doing this based on the model and you need to modify it to work with the package. 
```
public function getMutualFollowers()
{
    // Get the list of all user IDs that you are following
    $followings = Follow::where('follower_id', auth()->id())
        ->pluck('following_id')
        ->all();

    // Get the list of all user IDs that are following you
    $followers = Follow::where('following_id', auth()->id())
        ->pluck('follower_id')
        ->all();

    // Find the intersection between the two arrays to get the mutual follower IDs
    $mutualFollowerIds = array_intersect($followings, $followers);

    // Get the mutual followers from the database
    $mutualFollowers = User::whereIn('id', $mutualFollowerIds)->get();

    // Get the count of the mutual followers
    $count = $mutualFollowers->count();

    // Get 3 random names from the mutual followers collection
    $names = $mutualFollowers->random(3)->pluck('name')->all();

    return [        'count' => $count,        'names' => $names,    ];
}

```

**Comment by ArtMin96** [comment]
@ams-ryanolson Thanks. You can use `whereIntegerInRaw` instead of `whereIn`. Today I saw that this works faster with large numbers.

**Comment by ams-ryanolson** [comment]
@ArtMin96 ok awesome, I was doing that on the fly while working on other projects. Feel free to post your final code.

**Comment by ArtMin96** [comment]
@ams-ryanolson Ok :thumbsup:

**Comment by overtrue** [comment]
@ams-ryanolson 👍
