### ISSUE TITLE
[ERROR] After running command - SSL Issues

### ISSUE THREAD

**Issue by OfficialJens** [overtrue/laravel-follow#187]
For my school assignment it was recommended to use this extension.

If I run this command: `composer require overtrue/laravel-follow -vvv`
I get the following result: https://prnt.sc/B1GRXUees3kn | https://prnt.sc/RySRg0M7Sl_L

I work localhost, I use XAMPP MySQL, Laravel 10 and PHP 8.1

**Comment by overtrue** [comment]
Doesn't seem to be a problem, so it doesn't end up working properly？

**Comment by OfficialJens** [comment]
It just doesn't work with these errors.

**Comment by overtrue** [comment]
try to use following command:
```bash
composer require overtrue/laravel-follow
```

please paste the output.

**Comment by BradBin** [comment]
I have no idea

**Comment by hanchunlinzyf** [comment]
测试

**Comment by anbaichao1224** [comment]
学习watch
