### ISSUE TITLE
php artisan vendor:publish does not publish the migration or config

### ISSUE THREAD

**Issue by Xatta-Trone** [overtrue/laravel-follow#188]
Version: 5.0.1
Laravel: 9.19

Output from the console

`pa vendor:publish`

  Which provider or tag's files would you like to publish?
  Publish files from all providers and tags listed below ......................................................................................... 0
  Provider: BenSampo\Enum\EnumServiceProvider .................................................................................................... 1
  Provider: Cviebrock\EloquentSluggable\ServiceProvider .......................................................................................... 2
  Provider: Illuminate\Foundation\Providers\FoundationServiceProvider ............................................................................ 3
  Provider: Illuminate\Mail\MailServiceProvider .................................................................................................. 4
  Provider: Illuminate\Notifications\NotificationServiceProvider ................................................................................. 5
  Provider: Illuminate\Pagination\PaginationServiceProvider ...................................................................................... 6
  Provider: KitLoong\AppLogger\AppLoggerServiceProvider .......................................................................................... 7
  Provider: Laravel\Sail\SailServiceProvider ..................................................................................................... 8
  Provider: Laravel\Sanctum\SanctumServiceProvider ............................................................................................... 9
  Provider: Laravel\Tinker\TinkerServiceProvider ................................................................................................ 10
  Provider: Overtrue\LaravelFollow\FollowServiceProvider ........................................................................................ 11
  Provider: Rakutentech\LaravelRequestDocs\LaravelRequestDocsServiceProvider .................................................................... 12
  Provider: Spatie\HttpLogger\HttpLoggerServiceProvider ......................................................................................... 13
  Provider: Spatie\LaravelIgnition\IgnitionServiceProvider ...................................................................................... 14
  Tag: config ................................................................................................................................... 15
  Tag: flare-config ............................................................................................................................. 16
  Tag: ignition-config .......................................................................................................................... 17
  Tag: laravel-errors ........................................................................................................................... 18
  Tag: laravel-mail ............................................................................................................................. 19
  Tag: laravel-notifications .................................................................................................................... 20
  Tag: laravel-pagination ....................................................................................................................... 21
  Tag: migrations ............................................................................................................................... 22
  Tag: request-docs-assets ...................................................................................................................... 23
  Tag: request-docs-config ...................................................................................................................... 24
  Tag: request-docs-views ....................................................................................................................... 25
  Tag: sail ..................................................................................................................................... 26
  Tag: sail-bin ................................................................................................................................. 27
  Tag: sail-docker .............................................................................................................................. 28
  Tag: sanctum-config ........................................................................................................................... 29
  Tag: sanctum-migrations ....................................................................................................................... 30
  Tag: stubs .................................................................................................................................... 31
  Tag: translations ............................................................................................................................. 32
❯ `--provider=Overtrue\LaravelFollow\FollowServiceProvider`

?[37;41m [ERROR] Value "--provider=Overtrue\LaravelFollow\FollowServiceProvider" is invalid                                     

?[32m  ?[39m?[39;1mWhich provider or tag's files would you like to publish??[39;22m
  ?[33mPublish files from all providers and tags listed below?[39m ?[90m.........................................................................................?[39m 0
  ?[90mProvider:?[39m BenSampo\Enum\EnumServiceProvider ?[90m....................................................................................................?[39m 1
  ?[90mProvider:?[39m Cviebrock\EloquentSluggable\ServiceProvider ?[90m..........................................................................................?[39m 2
  ?[90mProvider:?[39m Illuminate\Foundation\Providers\FoundationServiceProvider ?[90m............................................................................?[39m 3
  ?[90mProvider:?[39m Illuminate\Mail\MailServiceProvider ?[90m..................................................................................................?[39m 4
  ?[90mProvider:?[39m Illuminate\Notifications\NotificationServiceProvider ?[90m.................................................................................?[39m 5
  ?[90mProvider:?[39m Illuminate\Pagination\PaginationServiceProvider ?[90m......................................................................................?[39m 6
  ?[90mProvider:?[39m KitLoong\AppLogger\AppLoggerServiceProvider ?[90m..........................................................................................?[39m 7
  ?[90mProvider:?[39m Laravel\Sail\SailServiceProvider ?[90m.....................................................................................................?[39m 8
  ?[90mProvider:?[39m Laravel\Sanctum\SanctumServiceProvider ?[90m...............................................................................................?[39m 9
  ?[90mProvider:?[39m Laravel\Tinker\TinkerServiceProvider ?[90m................................................................................................?[39m 10
  ?[90mProvider:?[39m Overtrue\LaravelFollow\FollowServiceProvider ?[90m........................................................................................?[39m 11
  ?[90mProvider:?[39m Rakutentech\LaravelRequestDocs\LaravelRequestDocsServiceProvider ?[90m....................................................................?[39m 12
  ?[90mProvider:?[39m Spatie\HttpLogger\HttpLoggerServiceProvider ?[90m.........................................................................................?[39m 13
  ?[90mProvider:?[39m Spatie\LaravelIgnition\IgnitionServiceProvider ?[90m......................................................................................?[39m 14
  ?[90mTag:?[39m config ?[90m...................................................................................................................................?[39m 15
  ?[90mTag:?[39m flare-config ?[90m.............................................................................................................................?[39m 16
  ?[90mTag:?[39m ignition-config ?[90m..........................................................................................................................?[39m 17
  ?[90mTag:?[39m laravel-errors ?[90m...........................................................................................................................?[39m 18
  ?[90mTag:?[39m laravel-mail ?[90m.............................................................................................................................?[39m 19
  ?[90mTag:?[39m laravel-notifications ?[90m....................................................................................................................?[39m 20
  ?[90mTag:?[39m laravel-pagination ?[90m.......................................................................................................................?[39m 21
  ?[90mTag:?[39m migrations ?[90m...............................................................................................................................?[39m 22
  ?[90mTag:?[39m request-docs-assets ?[90m......................................................................................................................?[39m 23
  ?[90mTag:?[39m request-docs-config ?[90m......................................................................................................................?[39m 24
  ?[90mTag:?[39m request-docs-views ?[90m.......................................................................................................................?[39m 25
  ?[90mTag:?[39m sail ?[90m.....................................................................................................................................?[39m 26
  ?[90mTag:?[39m sail-bin ?[90m.................................................................................................................................?[39m 27
  ?[90mTag:?[39m sail-docker ?[90m..............................................................................................................................?[39m 28
  ?[90mTag:?[39m sanctum-config ?[90m...........................................................................................................................?[39m 29
  ?[90mTag:?[39m sanctum-migrations ?[90m.......................................................................................................................?[39m 30
  ?[90mTag:?[39m stubs ?[90m....................................................................................................................................?[39m 31
  ?[90mTag:?[39m translations ?[90m.............................................................................................................................?[39m 32
?[1m❯ ?[22m

**Comment by Xatta-Trone** [comment]
How to publish the migration and config from here ?

**Comment by overtrue** [comment]
input number `11` and commit.

**Comment by Xatta-Trone** [comment]
Ohh...sorry for this silly mistake. I forgot that I could use the numbers. I was trying with config and provider flags. Pardon my ignorance.
