### ISSUE TITLE
Error after upgrade to 5.1.0

### ISSUE THREAD

**Issue by keyur555** [overtrue/laravel-follow#189]
Hello,

I upgraded to the latest version and did the migrations, and now I get this error which I can not figure out if it is a bug in the package or my error. I also use both new traits in user model like this:

```php
use Overtrue\LaravelFollow\Traits\Followable;
use Overtrue\LaravelFollow\Traits\Follower;
```

Then when I use this: `$user->followings()->count()`

Then I get this error:

```php
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.user_id' in 'where clause' (Connection: mysql, SQL: select count(*) as aggregate from `users` where `users`.`user_id` = 26 and `users`.`user_id` is not null)
```

My configuration is this:
```php

return [
    'uuids' => false,

    'user_foreign_key' => 'user_id',

    'followables_table' => 'followables',

    'followables_model' => User::class,
];

```

Do you know how to solve it? Thank you a lot

**Comment by overtrue** [comment]
What version was it before the upgrade?

**Comment by keyur555** [comment]
@overtrue I upgraded from 4.1.0 and did all the migration as described in the releases

**Comment by keyur555** [comment]
I can not find solution. No one else experience the issue?

**Comment by MartinsOnuoha** [comment]
@keyur555 after publishing the config files and migrations, and running `artisan migrate` did you check your database to see if the missing column exists? check the `followables` table if it exists and if your migration was successful

**Comment by overtrue** [comment]
@keyur555 According to [the semantic versioning specification](https://semver.org/), 4.x to 5.x is a major release, which usually means that there are destructive changes, there is no way to upgrade directly, you have to upgrade manually, you can treat it as two completely different versions, so you need to install and modify your code from scratch according to the 5.x documentation in order to use it properly, sorry for the long delay in getting back to you.

**Comment by keyur555** [comment]
Thank you for investigate @overtrue @MartinsOnuoha 

I update each version manually with migrations and other steps described in release notes from each version. My database table structure now is looks like this:

![Screen Shot 2023-04-19 at 6 59 31 PM](https://user-images.githubusercontent.com/92687884/233147446-9cb9aefb-b390-4343-9d03-b79ce08ec75b.png)

I use integer for polymorph class type for speed and less storage, I don't think it's the problem.

Do you see what can be wrong? I still use some code I post above.

For me it is interesting because from error it wants find 'user_id' column on 'users' table which don't exist and I don't know why

**Comment by overtrue** [comment]
please paste the  User model.

**Comment by keyur555** [comment]
@overtrue

As example, I get error when this function called: `$user->followings()->count()` and on `$user->follow($otherUser)` too.

I think something is wrong with the `followings()` relationship because I see in code that `follow` method also use it. When I inspect code it say it is HasMany but it should be Morph?

Here the user model:

```php
<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Scout\Searchable;
use Overtrue\LaravelFavorite\Traits\Favoriter;
use Overtrue\LaravelFollow\Traits\Followable;
use Overtrue\LaravelFollow\Traits\Follower;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable, Follower, Followable, Favoriter, Searchable, HasFactory;

    protected $guarded = [];

    protected $hidden = [
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'settings' => 'array',
    ];

    protected static function newFactory()
    {
        return UserFactory::new();
    }
}
```

**Comment by keyur555** [comment]
Hello, after 2 week I found the problem. I use User model in config, but when I use Followable like in default config then it works, but with other side effects.

I think it is bug in code for that case.

Thank you for your help :)

**Comment by overtrue** [comment]
```php
 'followables_model' => User::class,
```

the `followables_model` means the model that stores the relations, not the User Model.

**Comment by overtrue** [comment]
Unless you inherit the default relational model(https://github.com/overtrue/laravel-follow/blob/5.x/src/Followable.php) and do some enhancement methods, you don't need to modify it

**Comment by keyur555** [comment]
@overtrue I see it makes sense.

I noticed that followers() returns`User` models, but followings() returns the `Followable` morph model. Shouldn't both return users models? This is what breaks my tests from retrieving followings and followers. Only followings tests are broken but not for followers.

Should not both return User models?

Edit: Before version 5 it both returns Users models, but not since v5

**Comment by overtrue** [comment]
@keyur555 FYI: https://github.com/overtrue/laravel-follow/issues/170

**Comment by keyur555** [comment]
I had to change many queries, but it works now. Thank you for support
