### ISSUE TITLE
Count function

### ISSUE THREAD

**Issue by exzib** [overtrue/laravel-follow#19]
Could we have a ->count() function?

Ex: $user->followers()->count()

That perhaps is cached, right now this is how it looks like in debugbar:
https://i.imgur.com/vvI5KPu.png

Just to count a users followers.

**Comment by overtrue** [comment]
```php
>>> User::find(1)->followers();
=> Illuminate\Database\Eloquent\Relations\MorphToMany {#919}
>>> User::find(1)->followers()->count();
=> 1
```
