### ISSUE TITLE
getting "general error" when attempting to use UUIDs

### ISSUE THREAD

**Issue by eriksays** [overtrue/laravel-follow#196]
First of all, thank you for this library.

I have installed (laravel 10) and add the traits to the User Model and run the migrations. 

I am using UUIDs for the user id and have set 'uuids' to true in the config/follow.php

I have a UserController with a follow and unfollow method

`public function follow(User $user) {

        if (Auth::user() == $user) {
            //error, cannot follow yourself
            $request->session()->flash('error', 'You cannot follow yourself');
            return back()->withInput();
        }

        if (Auth::user()->isFollowing($user)) {
            //error, already following
            $request->session()->flash('error', 'You are already following ' . $user->name);
            return back()->withInput();
        }

        //here we are -- we can follow this user
        Auth::user()->follow($user);

    }

`

upon submission (url here: http://localhost/user/follow/406339cb-d3e7-410e-bd8b-6c7dbd2b891e)

I receive the following error:

`SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'f7e597b8-8ec0-4ba0-a871-7fdf4b2464da' for column 'user_id' at row 1

insert into
  `followables` (
    `followable_id`,
    `followable_type`,
    `user_id`,
    `accepted_at`,
    `id`,
    `updated_at`,
    `created_at`
  )
values
  (
    406339cb - d3e7 - 410e - bd8b - 6c7dbd2b891e,
    App \ Models \ User,
    f7e597b8 - 8ec0 - 4ba0 - a871 - 7fdf4b2464da,
    2023 -07 -03 16: 09: 25,
    998f2398 - 4ae2 -47e2 - af3f - 5da4fb1afe4d,
    2023 -07 -03 16: 09: 25,
    2023 -07 -03 16: 09: 25
  )`

Thank you for any suggestions.

**Comment by eriksays** [comment]
updated the database migration to as follows:

`Schema::create(config('follow.followables_table', 'followables'), function (Blueprint $table) {
            $table->uuid('id');
            $table->uuid(config('follow.user_foreign_key', 'user_id'))->index()->comment('user_id');
            if (config('follow.uuids')) {
                $table->uuidMorphs('followable');
            } else {
                $table->morphs('followable');
            }

            $table->timestamp('accepted_at')->nullable();
            $table->timestamps();

            $table->index(['followable_type', 'accepted_at']);
        });`

this seems to have resolved it.

Thanks

**Comment by overtrue** [comment]
You should update the config first before migrating, because this line depends on the config value: https://github.com/overtrue/laravel-follow/blob/5.x/migrations/2022_05_02_000000_create_followables_table.php#L14

**Comment by iRajul** [comment]
If user model is using Uuid primary key, then we need to change migration file manually to 
`$table->uuid('user_id')->index()->comment('user_id');`  Right?

**Comment by overtrue** [comment]
yes

Rajul ***@***.***>于2025年2月2日 周日01:10写道：
