### ISSUE TITLE
Unable to Handle UUIDs

### ISSUE THREAD

**Issue by Junaid-PK** [overtrue/laravel-follow#199]
When your User Model is using UUIDs. The Package gives the following Error:

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'followable_id' at row 1

**Comment by overtrue** [comment]
you must update the config file (config/follow.php, set `uuids` to true) before running migrate to support uuids.

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-follow/blob/5.x/migrations/2022_05_02_000000_create_followables_table.php#L14-L18
