### ISSUE TITLE
[Need Suggestion] Could I add is_approved in followables table?

### ISSUE THREAD

**Issue by a-ssassi-n** [overtrue/laravel-follow#20]
I am looking to make something like Instagram where user can make their profile private and when someone follows a user, they would have to approve it.

I have added a new column `is_private` to the `users` table and `is_approved` to the `followables` table.

Currently I am getting a user followers with this:   
`$allfollowers = $user->followers()->get();`

What should I do to check for `is_approved` field?
Any suggestion will be really appreciated.

Thank you.

**Comment by overtrue** [comment]
@a-ssassi-n You can use pivot feature of laravel: https://laravel.com/docs/5.7/eloquent-relationships#updating-many-to-many-relationships

```php
// follow
$user->follow($other, ['is_approved' => false]); // maybe default as false

//approve
$user->followers()->updateExistingPivot($other->id, ['is_approved' => true]);

// access pivot attributes
foreach ($user->followers as $follower) {
       $follower->pivot->is_approved; 
}
```

**Comment by lukecurtis93** [comment]
Hi I feel like i need to update this issue for a specific issue I'm having.

I need to grab the `is_approved` parameter for example. Updating is fine but on my backend I'm unable to query this relationship I feel like the following is the reason:
https://github.com/overtrue/laravel-follow/blob/master/src/Traits/CanFollow.php#L108

Is there a way we can override or add in additional `withPivot` attributes?

**Comment by MrEduar** [comment]
So adding that colunma right now is not convenient until you fix the bug? @overtrue
