### ISSUE TITLE
Cache likes, hasliked and anything else

### ISSUE THREAD

**Issue by exzib** [overtrue/laravel-follow#22]
Hey there.

I honestly love this package, I use it for my platform and it is working so well it's really impressive, well done!

However, this is not scaled for larger scale applications, I am using it for my platform with around 25000 users, we have a dashboard where we have a facebook like timeline, here is a screenshot:

https://i.imgur.com/r4LGdlx.png

The dashboard is the first thing that loads in, it loads in the latest 10 posts and displays the post one by one, for each post you can like it and see if you liked it, the same goes for comments on status as you can see here:

https://i.imgur.com/RnwyVsY.png

Now the issue we are seeing with this package is with the functions:

hasLiked()
getLikers()

The returns from there functions is not cached using Laravel Cache, therefor everytime a user loads in the dashboard it will query the database using the above functions (hasLiked, getLikers) on each post and each comment.

You may wonder what is the bad about this, well imagine we have 10 posts, each post has 10 comments.

When you load in the dashboard it would run hasLiked on each post and each comment, that means it queries the database 100 times everytime you load the dashboard.
Then for each comment and status it will also get all the likers, what happens now is that it queries the database again 100 times and for each comment and since we want to also receive the avatar, username and id of each commenter it will also query the user table an additional time for each comment.

I hope this makes sense.

How can you resolve this issue?
https://laravel.com/docs/5.4/cache

For example whenever like() or unlike() gets called, you could either set a key that is something like this when you like something:
{UserID}:hasLiked:{ModelName}:{ModelID}

And then remove it when ->unlike is called

Then you just see if the key exists using ->hasLiked

Could you please look into if this is possible, I am currently looking into implementing it myself in the user trait like so:
https://i.imgur.com/gv4wHag.png

And myself remove or set the key in controllers.

Thank you for this amazing plugin, feel free to use us as an example of use: https://altpocket.io (We use the following part for each user aswell! =))

**Comment by Mombuyish** [comment]
Using this:

```
//on your model with CanBeLiked
    public function auth_like()
    {
        return $this->likers()->where('user_id', auth()->id());
    }
```

on controller or service:
```
Post::where()->with('auth_like')->paginate(12);
```
view:
```
@if($post->auth_like)
```

**Comment by overtrue** [comment]
You can add a method to User model just like this:

```php

.
.
.
public function getCachedFollowers() 
{

    $key = sprintf("user:%s:followers", $this->getKey());

    return Cache::remember($key, 60, function(){
        return $this->followers();
    });
}
```
