### ISSUE TITLE
 Invalid relation definition Error

### ISSUE THREAD

**Issue by abhi-cognitivo** [overtrue/laravel-follow#27]
Hi, I am trying to implement this package, with the following code...

```
$profile = Profile::find($profile->id);
$userProfile = Profile::find(Auth::user()->profile_id);

$userProfile->follow($profile, 'App\Profile');
```

I have updated the tables to use profile_id instead of user_id. I am not sure if this is causing the issue, but am getting the following error:

 Exception
Invalid relation definition.

    protected static function getRelationTypeFromRelation(MorphToMany $relation)
    {
        $wheres = array_pluck($relation->getQuery()->getQuery()->wheres, 'value', 'column');
 
        if (empty($wheres['followables.relation'])) {
            throw new \Exception('Invalid relation definition.');
        }
 
        return $wheres['followables.relation'];
    }

**Comment by overtrue** [comment]
plz show me the `App\Profile` used traits.

**Comment by abhi-cognitivo** [comment]
Hi, thanks for your quick response...

use Overtrue\LaravelFollow\Traits\CanFollow;
use Overtrue\LaravelFollow\Traits\CanBeFollowed;

class Profile extends Model
{
use ..., CanFollow, CanBeFollowed;
}

I have both a Profile and a User table. This is because a Profile can be a user and not at the same time, such as a brand or celebrity profile for example.

This is the last line that hits before the Exception mentioned above.
    public static function attachPivotsFromRelation(MorphToMany $morph, $targets, $class)
    {
        return self::formatTargets($targets, $class, [
            'relation' => self::getRelationTypeFromRelation($morph), [<-- This is Causing the problem]
            'created_at' => Carbon::now()->format(config('follow.date_format', 'Y-m-d H:i:s')),
        ]);
    }
 


I have updated the code try to get it to work with User table and Profile but still no use. Please any help would be greatly appreciated!

**Comment by overtrue** [comment]
@abhi-cognitivo plz test on master branch.

**Comment by abhi-cognitivo** [comment]
Thanks for your quick reply. The original problem now seems to work, but I am getting a problem with the sql query being fired.

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profile_id' in 'where clause' (SQL: select `followable_id` from `profile_followers` where `relation` = follow and `profile_id` = 1 and `followable_type` = App\Profile)`

I have noticed you updated the Migration File. I am now running the installation code again to get the new migration file.

**Comment by abhi-cognitivo** [comment]
Ok, so I checked your new code, and it seems that the 

`$table->unsignedInteger('user_id');`

is hard coded but you are dynamically calling the column and thus it is showing profile_id.
This code would work perfectly if the table was user, but not so much if you change the table name.

Could you change this line
$table->unsignedInteger('user_id');
to
$table->unsignedInteger('follow.users_table_primary_key', 'user_id');

This way your config file create the appropriate name for the column and table being referenced.

**Comment by abhi-cognitivo** [comment]
Fyi, I manually changed the migration file to reflect profile_id and it worked flawless. So if you could update that last part I think you would have a really configurable following package.

Thanks for your help!

**Comment by overtrue** [comment]
@abhi-cognitivo https://github.com/overtrue/laravel-follow/commit/a6962d6a5b9c6f898d8b6b06156bcddffe886dce

**Comment by overtrue** [comment]
❤️

**Comment by abhi-cognitivo** [comment]
Fantastic! thanks
