### ISSUE TITLE
使用时不用新建一个表来存储关注吗？

### ISSUE THREAD

**Issue by zwl1619** [overtrue/laravel-follow#3]
使用时不用新建一个表来存储关注吗？

**Comment by overtrue** [comment]
@zwl1619 所以你根本没看 readme?

**Comment by zwl1619** [comment]
看了，是不是应该在`php artisan vendor:publish`后面加一个步骤：php artisan migrate，会更完整。

**Comment by overtrue** [comment]
@zwl1619 

1. 文档已经更新
2. 是因为没发版的原因，已经发版了：[1.1.0](https://github.com/overtrue/laravel-follow/releases/tag/1.1.0)
