### ISSUE TITLE
Nothing added to database

### ISSUE THREAD

**Issue by shrikanth003** [overtrue/laravel-follow#37]
I have tried the following but it doesn't work

`
public function followProfessional($slug)
    {
      $professional = Professional::where('slug', $slug)->first();
      if(! $professional) {

         return redirect()->back()->with('error', 'Professional does not exist.');
       }

      $user = Auth::user()->id;
      $user->follow($professional);
      return redirect()->back()->with('success', 'You are currently following this professional.');
    }
`

And in my view 

`
<a href="{{ url('professionals/'.$professional->category->slug.'/'.$professional->slug.'/follow') }}" class="btn btn-sm white">Follow</a>
`

And in my route
`Route::get('professionals/{professionalcategory}/{slug}/follow', 'ProfessionalController@followProfessional')->name('professional.follow');`

When i click on the follow button the page just refreshes back but doesn't add anything to the followables table

Could anyone help me out in this?

**Comment by overtrue** [comment]
```php
$user = Auth::user()->id; 
$user->follow($professional);
```

`$user` is an integer, not an object.

**Comment by shrikanth003** [comment]
So how to solve this? I'm stuck at this point

**Comment by overtrue** [comment]
plz paste the User and Professional Model used traits.

**Comment by shrikanth003** [comment]
User.php
`
use Overtrue\LaravelFollow\Traits\CanFollow;
use Overtrue\LaravelFollow\Traits\CanLike;
use Overtrue\LaravelFollow\Traits\CanFavorite;
use Overtrue\LaravelFollow\Traits\CanVote;

use CanFollow; use CanLike; use CanFavorite; use CanVote;
`

Professional.php
use Overtrue\LaravelFollow\Traits\CanBeFollowed;
use Overtrue\LaravelFollow\Traits\CanBeLiked;

use CanBeLiked; use CanBeFollowed;

**Comment by overtrue** [comment]
Did you confirmed that `$user->follow($professional)` was processed?

**Comment by shrikanth003** [comment]
I checked in the database and nothing has been added.

**Comment by overtrue** [comment]
you can test it in Tinker:

```php
$user = User::find(1);
$professional = Professional::find(1); 

$user->follow($professional); 
```

**Comment by shrikanth003** [comment]
That adds a record in the database when i followed your code and tested in tinker

**Comment by shrikanth003** [comment]
Here is the link with the screenshot `[https://ibb.co/fbLhCn](https://ibb.co/fbLhCn)`

**Comment by overtrue** [comment]
so, plz check you controller code.

**Comment by shrikanth003** [comment]
`public function followProfessional($slug)
    {
      $professional = Professional::where('slug', $slug)->first();
      if(! $professional) {

         return redirect()->back()->with('error', 'Professional does not exist.');
       }

      $user = Auth::user();
      $user->follow($professional);
      return redirect()->back()->with('success', 'You are currently following this professional.');
    }`

Is this code right? I know im making a mistake somewhere

**Comment by overtrue** [comment]
Sorry, You can using dd() function to debug you code, confirm every variable is expected.

**Comment by shrikanth003** [comment]
When i removed this from the controller code above, it adds a record but adds a 0 in followable_id
```
if(! $professional) {
         return redirect()->back()->with('error', 'Professional does not exist.');
 }
```

dd() gives me a null displayed nothing else

**Comment by overtrue** [comment]
`dd($professional);`

**Comment by shrikanth003** [comment]
I mean dd($professional); gives me a null. Here are the screenshots
1.  https://ibb.co/ijUCdS
2. https://ibb.co/f14657

and the code
```
public function followProfessional($slug)
    {
      $professional = Professional::where('slug', $slug)->first();
      
      $user = Auth::user();
      $user->follow($professional);
      dd($professional);
    }
```

**Comment by overtrue** [comment]
So, The result is you `Professional::where('slug', $slug)->first()` cannot find the `$professional`.

**Comment by overtrue** [comment]
every thing is OK, but problem is there is no matched slug professional exists.

**Comment by shrikanth003** [comment]
But if you see in the image 1. i sent. When i tested in the tinker it added App\Models\Professional to the followable type but when i tried with the code above from view button it added App\Models\User; 

Is that also an error?

**Comment by shrikanth003** [comment]
I changed the code to 
```
public function followProfessional(ProfessionalCategory $professionalcategory, $slug)
    {
      $professional = Professional::where('slug', $slug)->first();

      $user = Auth::user();
      $user->follow($professional);
      dd($professional);
    }
```

and now dd shows 
```
Professional {#378 ▼
  #appends: array:1 [▶]
  #table: "professionals"
  #fillable: array:27 [▶]
  #connection: "mysql"
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:33 [▶]
  #original: array:33 [▶]
  #changes: []
  #casts: []
  #dates: []
  #dateFormat: null
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #hidden: []
  #visible: []
  #guarded: array:1 [▶]
  #forceDeleting: false
  #autoTagTmp: null
  #autoTagSet: false
```

And the record is added to the database with the right followable type App\Models\Professional

Thank you so much @overtrue  for your valuable time.

I really love your package. More than that the support you provided here. Wonderful

**Comment by overtrue** [comment]
😆
