### ISSUE TITLE
Error with user_id

### ISSUE THREAD

**Issue by abhi-cognitivo** [overtrue/laravel-follow#38]
Hi, upon continued analysis, it seems you have manually written user_id in quite a few places.
I just stumbled upon one:

`$profile->isFollowedBy(Auth::user())`

This throws an error: 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_id' in 'where clause' (SQL: select exists(select * from `profiles` inner join `profile_followers` on `profiles`.`id` = `profile_followers`.`profile_id` where `profile_followers`.`followable_id` = 1 and `profile_followers`.`followable_type` = App\Profile and `profile_followers`.`relation` = follow and `user_id` = 1) as `exists`)

```
    public static function isRelationExists(Model $model, $relation, $target, $class = null)
    {
        $target = self::formatTargets($target, $class ?: config('follow.user_model'));
 
        return $model->{$relation}($target->classname)
                        ->where($class ? 'followable_id' : 'user_id', head($target->ids))->exists();
    }
```

Could you update the user_id to the config value. 

Just fyi I will try to download the code and help you with this, but if you can fix this particular one would be a great help thanks.

**Comment by overtrue** [comment]
@abhi-cognitivo plz try again.

**Comment by abhi-cognitivo** [comment]
public static function isRelationExists(Model $model, $relation, $target, $class = null)
    {
        $target = self::formatTargets($target, $class ?: config('follow.user_model'));
 
        return $model->{$relation}($target->classname)
                        ->where($class ? 'followable_id' : 'user_id', head($target->ids))->exists();
    }

I justed updated the code, but still no help. If you notice it is still calling user_id directly.

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-follow/commit/36ad4686abe7013ba3893da0f06270af3a5f532f

**Comment by abhi-cognitivo** [comment]
Sorry that was my mistake. I can see you updated the code, but running composer update is not bringing the new code into view. I am using @dev version. 

I will try in a little while. thanks!
