### ISSUE TITLE
Trait 'Overtrue\LaravelFollow\Traits\CanFollow' not found

### ISSUE THREAD

**Issue by a-ssassi-n** [overtrue/laravel-follow#4]
After `php artisan vendor:publish`  I migrated the tables.
My User Model looks like this:
```
<?php
namespace App;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Overtrue\LaravelFollow\Traits\CanBeFollowed;
use Overtrue\LaravelFollow\Traits\CanFollow;
class User extends Authenticatable
{
    use CanFollow, CanBeFollowed;
....
}
```
But I am getting
```
FatalErrorException in User.php line 11:
Trait 'Overtrue\LaravelFollow\Traits\CanFollow' not found
```

**Comment by overtrue** [comment]
`dev-master` ? the master branch has no release. so plz use the `dev-master` branch.

**Comment by a-ssassi-n** [comment]
I am using master v1.1.0. how to download dev-master. Can you please help.

**Comment by overtrue** [comment]
`$ composer require overtrue/laravel-follow:dev-master -vvv`

**Comment by a-ssassi-n** [comment]
Okay but I have already installed the master branch, so will installing dev-master overwrite it?

**Comment by overtrue** [comment]
just try it.

**Comment by a-ssassi-n** [comment]
Worked Thanks :+1:

**Comment by Shubhamlmp** [comment]
> `PHP Fatal error: Trait 'Overtrue\LaravelFollow\Traits\CanBeLiked' not found in D:\xampp\htdocs\blog\app\Post.php on line 11
> 
> ```
> Symfony\Component\Debug\Exception\FatalErrorException  : Trait 'Overtrue\LaravelFollow\Traits\CanBeLiked' not found
> at D:\xampp\htdocs\blog\app\Post.php:11
>  7| use Illuminate\Database\Eloquent\Model;
>  8|
>  9|
> 10|
>  > 11| class Post extends Model{
> 12|
> 13|         use CanBeLiked;
> 14|
> 15|     protected $fillable = ['title'];
> 
> 
> Whoops\Exception\ErrorException  : Trait 'Overtrue\LaravelFollow\Traits\CanBeLiked' not found
> at D:\xampp\htdocs\blog\app\Post.php:11
>  7| use Illuminate\Database\Eloquent\Model;
>  8|
>  9|
> 10|
> > 11| class Post extends Model{
> 12|
> 13|         use CanBeLiked;
> 14|
> 15|     protected $fillable = ['title'];
> 
> Exception trace:
> 
> 1   Whoops\Run::handleError("Trait 'Overtrue\LaravelFollow\Traits\CanBeLiked' not found", "D:\xampp\htdocs\blog\app\Post.php")
>   D:\xampp\htdocs\blog\vendor\filp\whoops\src\Whoops\Run.php:486
> 
> 2   Whoops\Run::handleShutdown()
>   [internal]:0
> ```
> 
> `
> 
> I have got this error.
> 
> Laravel - 5.6 LaravelFollow - 2.0.0

I also have the same problem is any one please help me

**Comment by overtrue** [comment]
looking at the package in your vendor directory to make sure you had install version 1.* .

**Comment by overtrue** [comment]
From 2.0 onwards, the original 1.x functionality has been split into multiple packages.

https://github.com/overtrue/laravel-follow/releases/tag/2.0.0
