### ISSUE TITLE
Call to a member function where() on array

### ISSUE THREAD

**Issue by hussein-elhussein** [overtrue/laravel-follow#40]
that's when i try to check if a model has down/up voted a another model ( model->hasUpvoted() )

**Comment by overtrue** [comment]
plz take a try with master code.

**Comment by xyxu** [comment]
测试可用，为啥不合并进去？
@overtrue

**Comment by overtrue** [comment]
@xyxu 你在说啥呢？合并什么？

**Comment by overtrue** [comment]
@xyxu 我明白了，相关的代码当天就已经合并了，只是没发版，刚才发了一版。
