### ISSUE TITLE
Get relationship date

### ISSUE THREAD

**Issue by derebaba** [overtrue/laravel-follow#43]
Hi,

Is there a way to get the date when the relationship was created?

**Comment by AdrianHL** [comment]
Hi @derebaba. The migration that creates the table that handles the relationship has `$table->timestamps();` in it so it should be possible to obtain the created with `->created_at`.

**Comment by derebaba** [comment]
So it means I need to get the relationships using a database query. Is there an easy way to do this (using relationship methods)? For example: when I call `$user->followings->first()->created_at`, I get the date when the user is created, not the date that the relationship was created.

**Comment by overtrue** [comment]
@derebaba 

```
$user->followings->first()->pivot->created_at
```

**Comment by derebaba** [comment]
Thanks for your help.
