### ISSUE TITLE
Likes are failing

### ISSUE THREAD

**Issue by sicsol** [overtrue/laravel-follow#48]
Great package you saved me a bunch of time from needed to build something like this. I just upgraded to 1.1.5 and realized my unit tests are failing.

It appears to be an issue with relationship mapping for the relationship type 'likes'.

Here is the output of my tests.

Exception: Invalid relation definition.

`/xxx/vendor/overtrue/laravel-follow/src/Follow.php:178
/xxx/vendor/overtrue/laravel-follow/src/Follow.php:132
/xxx/vendor/overtrue/laravel-follow/src/Follow.php:115
/xxx/vendor/overtrue/laravel-follow/src/Traits/CanLike.php:61`

you have the following set but likes aren't included

    const RELATION_LIKE = 'like';
    const RELATION_FOLLOW = 'follow';
    const RELATION_SUBSCRIBE = 'subscribe';
    const RELATION_FAVORITE = 'favorite';
    const RELATION_UPVOTE = 'upvote';
    const RELATION_DOWNVOTE = 'downvote';

    /**
     * @var array
     */
    protected static $relationMap = [
        'followings' => 'follow',
        'followers' => 'follow',
        'favoriters' => 'favorite',
        'favorites' => 'favorite',
        'subscriptions' => 'subscribe',
        'subscribers' => 'subscribe',
        'upvotes' => 'upvote',
        'upvoters' => 'upvote',
        'downvotes' => 'downvote',
        'downvoters' => 'downvote',
    ];

**Comment by overtrue** [comment]
@sicsol I'm sorry to reply to you until now, plz update to 1.1.6 and try it again.

**Comment by ismailcaakir** [comment]
@overtrue It worked great for me after updating. Thanks.

**Comment by overtrue** [comment]
@ismailcaakir 😄
