### ISSUE TITLE
Not able to follow multiple users

### ISSUE THREAD

**Issue by a-ssassi-n** [overtrue/laravel-follow#5]
When a Auth user (id: 1) follows user with id:2 
![cap1](https://cloud.githubusercontent.com/assets/7111734/25650040/c910954e-2ff7-11e7-9a12-49cf8385f500.PNG)

But when the same Auth user follows user with id:3, the column is replaced with 
![cap2](https://cloud.githubusercontent.com/assets/7111734/25650056/e538a8a6-2ff7-11e7-9fab-7031f6b336e4.PNG)

Also nothing is added in the followers table, it always remains empty!!
This is my code:
```
 public function userFollow($id)
    {
        $authuser = Auth::user();
        $user     = User::find($id);
        $authuser->follow($user);
        return redirect()->back()->with('message', 'Following User');
    }
    
    public function userUnfollow($id)
    {
        $authuser = Auth::user();
        $user     = User::find($id);
        $authuser->unfollow($user);
        return redirect()->back()->with('message', 'Unfollowing User');
    }
```
Am I doing something wrong?

**Comment by overtrue** [comment]
I will fix it.

**Comment by a-ssassi-n** [comment]
Please let me know how much time it will take to resolve this issue as I am working on a live project and it is urgent :)

**Comment by overtrue** [comment]
@a-ssassi-n plz update the package: 

```sh
$ composer update overtrue/laravel-follow -vvv
```

**Comment by a-ssassi-n** [comment]
composer update overtrue/laravel-follow -vvv OR composer require overtrue/laravel-follow:dev-master -vvv
Previously the master branch was not working na> https://github.com/overtrue/laravel-follow/issues/4
Is it working now? or should I download the `dev-master`?

**Comment by overtrue** [comment]
plz update and try again.

**Comment by a-ssassi-n** [comment]
Which branch? master or dev-master?

**Comment by overtrue** [comment]
yes

**Comment by a-ssassi-n** [comment]
Okay dev-master is now working as expected. I will let you know if I get any other buys.
Thank-you.

**Comment by overtrue** [comment]
OK,Thanks.
