### ISSUE TITLE
Duplicate publishing migration table

### ISSUE THREAD

**Issue by Mombuyish** [overtrue/laravel-follow#51]
I got some issue
my laravel and package are latest version
when I use `php artisan vendor:publish` and choosing 0(all published)
found CreateLaravelFollowTables exists two, and I found:
https://github.com/overtrue/laravel-follow/blob/master/src/FollowServiceProvider.php#L31

``` php
!class_exists('CreateLaravelFollowTables')
```
Not correctly working
if class exists should be return true and reverse boolean, so it should be `false`, but class_exists('CreateLaravelFollowTables') always return `false` and then reverse, so it always got `true` and always into condition to generate migration.

I have been try sometimes, but I no have any idea what's happen, anyone?

**Comment by Mombuyish** [comment]
@overtrue 這目前還沒有解決，要麻煩你查找一下了
目前新版本也是一樣的狀況
thanks.

**Comment by overtrue** [comment]
我現在在公司環境沒有個人相關的代碼庫，搭建也比較麻煩，公司有限制，你可以先查一下為啥 `class_exists` 會不存在，辛苦了，我只有晚上回家才接觸自己的項目環境。
