### ISSUE TITLE
这个版本有问题

### ISSUE THREAD

**Issue by kenfu** [overtrue/laravel-follow#6]
1、便是找不到CanBeLike之类的。
2、在使用 $post->likers()时  withPovit 又没有被定义。

挺喜欢这个插件的，希望作者能修正。

**Comment by overtrue** [comment]
请更新到 1.1.1

**Comment by kenfu** [comment]
感谢超哥！ 直接按照首页的安装吗？ 还是继续composer require overtrue/laravel-follow:dev-master -vvv
