### ISSUE TITLE
How to count how many upvotes a user has

### ISSUE THREAD

**Issue by martinetoye** [overtrue/laravel-follow#60]
Hi.

I wonder if any can help. 

Each user can Upvote and Post (Post Model).

I want to be able to count the number of upvote a user has received. for example

User has 5 Posts and each post has received 2 Upvotes. 

Total upvotes = 10.

I have tried

$user->posts->upvoters()->get()->count()

But this gives me upvoters is not on this collection.

Thanks in advance

**Comment by lukadriel7** [comment]
Hello, I just started and am planning to install this package but I think you should try:
$user->posts and then cycle through each post. if I am not mistaken, $user->posts gives you an array of model post which is why you may not be able to call upvoters() directly.

**Comment by overtrue** [comment]
> https://laravel.com/docs/5.6/eloquent-relationships#counting-related-models
