### ISSUE TITLE
How to sort favorite/like/etc. items by the favorite/like time.

### ISSUE THREAD

**Issue by iflamed** [overtrue/laravel-follow#67]
Example:
```php
$user->favorites()->orderBy('id', 'desc')->get();
```
This program will result a sorted collection by the favorites item's ID. Mostly, We need to sorted with the action time.

**Comment by overtrue** [comment]
```php
$user->favorites()->orderBy('pivot_created_at', 'desc')->get();
```

**Comment by iflamed** [comment]
Thanks, And I checked the migration file, `created_at` haven't set index.
