### ISSUE TITLE
getTargetsCollection() not working

### ISSUE THREAD

**Issue by Mathias88** [overtrue/laravel-follow#69]
Hi, I'm trying to get data with the getTargetsCollection() function in the event and I'm not making it.
This is the error:

`[2018-09-17 20:53:23] testing.ERROR: SQLSTATE[HY000]: General error: 25 column index out of range (SQL: select * from "posts" where "posts"."id" in (App\Models\Post, 1, upvote) and "posts"."deleted_at" is null) {"userId":1,"email":"shaun.johnston@example.com","exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 25 column index out of range (SQL: select * from \"posts\" where \"posts\".\"id\" in (App\\Models\\Post, 1, upvote) and \"posts\".\"deleted_at\" is null) at C:\\xampp\\htdocs\\Coderos\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 25 column index out of range at C:\\xampp\\htdocs\\Coderos\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:144, PDOException(code: HY000): SQLSTATE[HY000]: General error: 25 column index out of range at C:\\xampp\\htdocs\\Coderos\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:142)`

**Comment by overtrue** [comment]
This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)
