### ISSUE TITLE
1.1.8 Issue

### ISSUE THREAD

**Issue by snazy2000** [overtrue/laravel-follow#72]
Since moving from 1.1.7 to 1.1.8 I now get 

Incorrect syntax near the keyword 'IS'. (SQL: select [users].*, pivot_followables.user_id IS NOT NULL AS pivot_each_other, [followables].[followable_id] as [pivot_followable_id], [followables].[user_id] as [pivot_user_id], [followables].[followable_type] as [pivot_followable_type], [followables].[relation] as [pivot_relation], [followables].[created_at] as [pivot_created_at] from [users] inner join [followables] on [users].[id] = [followables].[user_id] left join [followables] as [pivot_followables] on [pivot_followables].[followable_type] = 'App\\Suggestion' and [pivot_followables].[followable_id] = [followables].[user_id] and [pivot_followables].[user_id] = [followables].[followable_id] where [followables].[followable_id] = 1066 and [followables].[followable_type] = App\Suggestion and [followables].[relation] = follow

when going $object->followers()->get()

**Comment by overtrue** [comment]
What db engine are you used?

**Comment by overtrue** [comment]
https://dev.mysql.com/doc/refman/8.0/en/working-with-null.html 

`IS NOT NULL` is a valid mysql syntax.

**Comment by snazy2000** [comment]
Using mssql :(


Sent from Yahoo Mail for iPhone


On Friday, October 26, 2018, 2:47 pm, 安正超 <notifications@github.com> wrote:


https://dev.mysql.com/doc/refman/8.0/en/working-with-null.html

IS NOT NULL is a valid mysql syntax.

**Comment by overtrue** [comment]
I got the reason. Sorry, I will fix that as soon as possible.

**Comment by overtrue** [comment]
@snazy2000 Plz take a try with master branch, if it works plz let me know.

**Comment by snazy2000** [comment]
Hi @overtrue 

I have just tried the fix and unfortunately still same error.

It doesn't look like what your doing there is supported in MSSQL 

Stephen

**Comment by snazy2000** [comment]
https://stackoverflow.com/questions/14962970/sql-query-if-value-is-null-then-return-1

**Comment by overtrue** [comment]
@snazy2000 Please paste the SQL.

**Comment by snazy2000** [comment]
select [users].*, [pivot_followables].[user_id] IS NOT NULL as [pivot_each_other], [followables].[followable_id] as [pivot_followable_id], [followables].[user_id] as [pivot_user_id], [followables].[followable_type] as [pivot_followable_type], [followables].[relation] as [pivot_relation], [followables].[created_at] as [pivot_created_at] from [users] inner join [followables] on [users].[id] = [followables].[user_id] left join [followables] as [pivot_followables] on [pivot_followables].[followable_type] = 'App\\Suggestion' and [pivot_followables].[followable_id] = [followables].[user_id] and [pivot_followables].[user_id] = [followables].[followable_id] where [followables].[followable_id] = 1066 and [followables].[followable_type] = App\Suggestion and [followables].[relation] = follow

**Comment by overtrue** [comment]
@snazy2000 I am sorry, I have not  SQL Server environment, So, plz do you best to debug and fix this problem, or use MySQL. Let me know if you resolved the bug. Thanks.

**Comment by snazy2000** [comment]
Can you advise what the need for the IS NOT NULL at that point?
If I remove it shows NULL in that field
Im used to the IS NOT NULL within the Where statements

**Comment by overtrue** [comment]
@snazy2000 https://github.com/overtrue/laravel-follow/issues/63 He want to get is follow each other.

**Comment by davisriska** [comment]
Im sadly having the same issue, as Im also using MSSQL. Locking the version on 1.1.7 for now. If only I could use MySQL I would. 😢 
@snazy2000 If you find a solution, please be so kind and post it here! 😅

**Comment by snazy2000** [comment]
@overtrue are you expecting this result

IF NOT NULL then set field = 1
IF NULL then set field = 0 ?

Or am I miss understanding?

**Comment by snazy2000** [comment]
If the above is correct then this should work?

(CASE WHEN [pivot_followables].[user_id] IS NOT NULL THEN 1 ELSE 0 END) as [pivot_each_other],

**Comment by overtrue** [comment]
Yes, but is it compatible with MySQL?

**Comment by snazy2000** [comment]
I dont have a mysql enviroment are you able to make a change and test that and i can test mssql? 


Sent from Yahoo Mail for iPhone


On Thursday, November 1, 2018, 1:31 am, 安正超 <notifications@github.com> wrote:


Yes, but is it compatible with MySQL?

**Comment by snazy2000** [comment]
Looking online case is supported in mysql in select statement so does look like would work


Sent from Yahoo Mail for iPhone


On Thursday, November 1, 2018, 1:31 am, 安正超 <notifications@github.com> wrote:


Yes, but is it compatible with MySQL?

**Comment by overtrue** [comment]
@snazy2000 plz take a try with master branch.

**Comment by snazy2000** [comment]
No More errors! :) See query below

select [users].*, (CASE WHEN [pivot_followables].[user_id] IS NOT NULL THEN 1 ELSE 0 END) as [pivot_each_other], [followables].[followable_id] as [pivot_followable_id], [followables].[user_id] as [pivot_user_id], [followables].[followable_type] as [pivot_followable_type], [followables].[relation] as [pivot_relation], [followables].[created_at] as [pivot_created_at] from [users] inner join [followables] on [users].[id] = [followables].[user_id] left join [followables] as [pivot_followables] on [pivot_followables].[followable_type] = 'App\\Suggestion' and [pivot_followables].[followable_id] = [followables].[user_id] and [pivot_followables].[user_id] = [followables].[followable_id] where [followables].[followable_id] = '1095' and [followables].[followable_type] = 'App\Suggestion' and [followables].[relation] = 'follow'

**Comment by overtrue** [comment]
😆
