### ISSUE TITLE
Keeping all the data in one table

### ISSUE THREAD

**Issue by taliptako** [overtrue/laravel-follow#75]
I like this package but what i wonder is why you keep all the data in one table when you search for user likes for example mysql should find followable_type first from all the followable types in the table and it can maybe increase query time ?

**Comment by overtrue** [comment]
Thanks, I am just put them all data into one table because these relations are same data structure, I have added index on `followable_type` column, so it shouldn't  increase the query time.

**Comment by overtrue** [comment]
Plz let me know If you has any other good idea. :smile:

**Comment by taliptako** [comment]
> Thanks, I am just put them all data into one table because these relations are same data structure, I have added index on `followable_type` column, so it shouldn't increase the query time.

It still increases the query time but for little projects it won't be a problem I think. I decided to use different packages for all my traits.I will use subscribable from yours. Thank you :D

**Comment by overtrue** [comment]
@taliptako Thanks. I will make some changes on next major version. Thanks for your advice.

**Comment by solwyvern** [comment]
Definitely need to have separate tables to have more scalability. You can have thousands of likes/favorites/bookmarks/etc... but all querying the same table

**Comment by overtrue** [comment]
@solwyvern Yes, I am working on this. and I have made a package for like/unlike: https://github.com/overtrue/laravel-like

**Comment by overtrue** [comment]
This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)
