### ISSUE TITLE
After update to 1.1.11, I get SQL integrity constraint violation

### ISSUE THREAD

**Issue by peterbrinck** [overtrue/laravel-follow#79]
I updated the package today, and after that, I received an SQL error when using `hasLiked`.

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
```

I'm using the `hasLiked` as it's used in the README, `$user->hasLiked($target)`

I downgraded the package to 1.1.10, and everything works again

**Comment by overtrue** [comment]
This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)
