### ISSUE TITLE
怎样获取某个用户关注的人和被关注的人? ReadMe写得很笼统

### ISSUE THREAD

**Issue by iVanilla** [overtrue/laravel-follow#8]
```
$user->followings();
$object->followers();
```
这样获取到的是什么对象? 是否需要用foreach遍历? 直接获取用户ID啥的不行
另外怎样统计用户关注/被关注的用户数量?

**Comment by overtrue** [comment]
这俩方法均支持传入目标类型：

```php
$user->followings(Post::class);
$object->followers(); // 这个返回肯定是用户类型了
```

**Comment by iVanilla** [comment]
@overtrue 这样返回的是object, 然而我不能通过`$user->followings(User::class)->name;`的方式获取此用户关注的用户名称, 这是不是一个集合, 需要用foreach来遍历?

**Comment by overtrue** [comment]
`$user->followings()` 获取用户关注中的人，必然是一个集合啊 😭

**Comment by iVanilla** [comment]
@overtrue 那么获取一个用户的粉丝和关注的人的数量用count来计算对吧

**Comment by overtrue** [comment]
嗯

**Comment by kenfu** [comment]
很奇怪，为什么用 @foreach无法把$user->followings(Post::class);列出来？

**Comment by overtrue** [comment]
@kenfu 结果是？有报错？

**Comment by kenfu** [comment]
没有报错。
我是用的两个模型，一个是POST，一个VIDEO，此时followables表里有3个App\Models\Topic和2个App\Models\Video的like数据。
$user->likes()->count()前端显示的是0
$user->likes(Topic::class)->count()前端显示3正常。

$videos = $user->likes(Video::class)到前端
但是用@foreach($videos as $video )时，无法取出值来，前端也没有报错。

**Comment by kenfu** [comment]
大神再不修改，我真的是要自己造轮子了，但是不甘啊！ 请问下，你的多态多对多关系是如何实现toggleLike的，这个厉害。

**Comment by overtrue** [comment]
调试为啥要看前端有没有啊？你不应该是  `dd($videos)` 就能知道结果么？

**Comment by kenfu** [comment]
这样的代码我看不懂，所以就笨方法了。

MorphToMany {#326 ▼
  #morphType: "followable_type"
  #morphClass: "App\User"
  #inverse: true
  #table: "followables"
  #foreignKey: "user_id"
  #relatedKey: "followable_id"
  #relationName: "likes"
  #pivotColumns: array:3 [▶]
  #pivotWheres: array:1 [▶]
  #pivotWhereIns: []
  #pivotCreatedAt: null
  #pivotUpdatedAt: null
  #using: null
  #query: Builder {#341 ▶}
  #parent: User {#343 ▶}
  #related: User {#337 ▶}
}

**Comment by overtrue** [comment]
哈哈，我知道问题所在了：试试 `$user->likes(Video::class)->get()`

**Comment by kenfu** [comment]
感谢大神！终于没放弃！ 这个在后端好用，能否改进下源码，让我直接在前端 $user->likes(topic)就可以选择我需要的东西。

$user->likes()列出我所有喜欢的，$user->likes('topic')列出沃Topic下的喜欢。

如果这个在后台，感觉传参数很麻烦，而且 Video::class 还需要在上面use App\Models\Video;对吗？

**Comment by overtrue** [comment]
> $user->likes()列出我所有喜欢的，$user->likes('topic')列出沃Topic下的喜欢

不行的，万一你要用它来查询就无解了。。。

> 而且 Video::class 还需要在上面use App\Models\Video;对吗？

是的，因为要支持多类型，所以如果要筛选类型就得自己传类型了

不过这个毕竟是 trait 嘛，所以你可以考虑在你的模型里添加方法：

```php
public function likeVideos() 
{
      return $this->likes(\App\Models\Video::class)->get();
}
```

然后 

```php
$user->likeVideos() 就可以得到全部啦
```
