### ISSUE TITLE
How to count relation?

### ISSUE THREAD

**Issue by r94ever** [overtrue/laravel-follow#84]
Hi,

I have a model App\User which is imported `CanLike` trait, and 2 models App\Post, App\Video which are imported `CanBeLiked`. Now I need to count how many likes an user has performed on these models (Post & Video).

As usual, I have used `withCount()` method like this:

``
$user = User::withCount(['likes'])->get();
``

or 

``
$user->likes()->count();
``

But the results of above code always were `0` all of the times. However, with `likes` method, it worked fine if I passed a param for it:

``$user->likes(\App\Post:class)->count();``

So, what I want to ask here is how can I count how many likes an user has performed on all `CanBeLiked` model with Laravel's `withCount()` method. All help is appreciated!

Thanks,

**Comment by overtrue** [comment]
@r94ever I am very sorry, it seems that this is an unfinished function, I will fix this problem in a very short time.

**Comment by r94ever** [comment]
@overtrue thanks for reply. Hope this will be fix soonly

**Comment by overtrue** [comment]
@r94ever plz use my new package: https://github.com/overtrue/laravel-like with dev-master version:

```php
$ composer require overtrue/laravel-like:dev-master
```

I will separate this package to multiple package.

**Comment by r94ever** [comment]
@overtrue I think the separation is better, but I am using this package for many project. So I wonder this one will still be maintained?

**Comment by overtrue** [comment]
yes, but I found that the design of this package is bag, so some features
can’t be implement.

r94ever <notifications@github.com>于2019年1月23日 周三下午7:00写道：

**Comment by aFluxx** [comment]
@overtrue , which features will get deprecated?

**Comment by overtrue** [comment]
@aFluxx All the existing features will be maintained, I will continue to develop several other packages to replace them.

**Comment by r94ever** [comment]
@overtrue thanks for your clearly

**Comment by overtrue** [comment]
@r94ever You are welcome.
