### ISSUE TITLE
Can you add group option for favorite and bookmark.

### ISSUE THREAD

**Issue by MoeCasts** [overtrue/laravel-follow#88]
如果能自定义收藏分组，这个功能会变得更好。

**Comment by overtrue** [comment]
This pack has a long history and the design wasn't perfect at the time, making it difficult to update now, I recently made a series of sub-packages of this bunch of relationships, you can try out the new package, sorry for the trouble!

- Follow: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)
- Like: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Favorite: [overtrue/laravel-favorite](https://github.com/overtrue/laravel-favorite)
- Subscribe: [overtrue/laravel-subscribe](https://github.com/overtrue/laravel-subscribe)
- Vote: overtrue/laravel-vote (working in progress)
- Bookmark: overtrue/laravel-bookmark (working in progress)

**Comment by overtrue** [comment]
收藏分组这个功能即将上线

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-favorite/issues/2

**Comment by overtrue** [comment]
@MoeCasts 抱歉，我想了一下，也看了目前各个产品的收藏夹功能，发现他们对收藏夹的属性定义都比较不通用，也就是说这块感觉应该是在应用层自己去设计模型比较合适，然后将此包的 migration 发布到应用下，增加收藏夹 ID 即可。

所以暂时先不在包里内置收藏夹功能了，后续如果有更好的方案再考虑。
