### ISSUE TITLE
N+1 problem when querying data

### ISSUE THREAD

**Issue by Obacm** [overtrue/laravel-follow#89]
`public function getUpVotersAttribute()
    {
        return $this->upvoters()->count();
    }`

What shall I do?

**Comment by overtrue** [comment]
https://laravel.com/docs/5.8/eloquent-relationships#eager-loading

**Comment by Obacm** [comment]
I want to get all the comments and get the likes and have already liked them.

**Comment by overtrue** [comment]
$comments->load('upvoters');

**Comment by Obacm** [comment]
This issue has been resolved. Thanks. 👍
