### ISSUE TITLE
Guest voting system.

### ISSUE THREAD

**Issue by xsaad67** [overtrue/laravel-follow#93]
Can i implement it to use for guest vote. I mean non auth users can be verify from ip address

What I've thought about it as

user_id -> nullable
--Add two columns
isGuest -> boolean default 0
ip/token ->(nullable) to verify guest

I've a limited knowledge of laravel just asking is this the right schema to go on?

**Comment by overtrue** [comment]
yes, your scheme design is right. but mayby you need implement it by yourself.

**Comment by xsaad67** [comment]
Ok thanks I'll try to update how far i can go
