### ISSUE TITLE
 Column not found: 1054 Unknown column 'member_id' in 'where clause' (SQL: select `followable_id` from `followables` 

### ISSUE THREAD

**Issue by cboy868** [overtrue/laravel-follow#96]
当使用的user模型类名非 User 而是Member 会报上面的错误

查看源码应该在morphedByMany中加入第四个参数 user_id，因为表中的列名是固定的

canFavorite class 
public function favorites($class = __CLASS__)
    {
        return $this->morphedByMany($class, config('follow.morph_prefix'), config('follow.followable_table'))
                    ->wherePivot('relation', '=', Follow::RELATION_FAVORITE)
                    ->withPivot('followable_type', 'relation', 'created_at');
    }

**Comment by overtrue** [comment]
Hi, 可以考虑更换为我刚拆分出来的包：https://github.com/overtrue/laravel-favorite
